<?php
/**
 * @file create.php - create a new database and a new db_connect_params.php file
 * @author Erel Segal
 * @date 2013-01-15
 */
error_reporting(E_ALL);
set_time_limit(0);

print "
# Create a new database for Tanakh Navigation Kit

## Requirements

* MySQL 8
* PHP 5-6 (but not 7)
* PHP-MySQL extension
";

$SCRIPT = dirname(__FILE__) . '/../../_script';

require_once("$SCRIPT/sql.php");
require_once("$SCRIPT/sql_backup.php");
require_once("$SCRIPT/coalesce.php");

show_create_page();
update_create_page();

function read($vartitle, $varname) {
	$default = coalesce($GLOBALS[$varname],"");
	print "$vartitle [$default]: "; $varvalue = trim(fgets(STDIN));
	$_POST[$varname] = $varvalue? $varvalue: $default;
}

function show_create_page() {
	@include_once(dirname(__FILE__) . "/db_connect_params.php"); // only if it exists
	set_coalesce($GLOBALS['root_username'], coalesce($GLOBALS['root_username'],'root'));
	set_coalesce($GLOBALS['root_password'], coalesce($GLOBALS['root_password'],''));
	set_coalesce($GLOBALS['db_host'], coalesce($GLOBALS['db_host'],'localhost'));
	set_coalesce($GLOBALS['db_name'], coalesce($GLOBALS['db_name'],'tnk1'));
	set_coalesce($GLOBALS['db_user'], coalesce($GLOBALS['db_user'],'tnk1'));
	set_coalesce($GLOBALS['db_pass'], coalesce($GLOBALS['db_pass'],'tnk1'));
	set_coalesce($GLOBALS['is_local'], coalesce($GLOBALS['is_local'],'false'));
	
	print "
## Credentials

";
	$_POST['db_host'] = $GLOBALS['db_host'];
	read("MySQL root username", "root_username");
	read("MySQL root password", "root_password");

	print "
## New database data

";
	read("New database name", "db_name");
	read("New user name", "db_user");
	read("New user password", "db_pass");
	print "Drop existing database if it exists? [no]: "; $drop_db = trim(fgets(STDIN));
	$_POST['drop_db']=($drop_db=='yes');
}


function update_create_page() {
	print "
## New database creation

";

	print "* create_database_and_user();
";	create_database_and_user();

	print "* create_db_connect_params();
";	create_db_connect_params();

	print "* require('db_connect.php');
";	require(dirname(__FILE__) . "/db_connect.php");

	print "* create_database_tables();
";	create_database_tables();

	print "* create_tnk_views();
";	create_tnk_views();

	print "

## Done!

Go to the main page: http://localhost/tnk1/

";
}


function create_database_and_user() {
	$link = sql_connect(
		$_POST['db_host'],
		$_POST['root_username'],
		$_POST['root_password']);
	
	if (!$link)
		die('Could not connect as $_POST[db_user]: ' . sql_get_last_message());

	if (isset($_POST['drop_db']))
		sql_query_or_die("DROP DATABASE IF EXISTS $_POST[db_name]");

	if (sql_database_exists($_POST['db_name'])) {
		echo "Database $_POST[db_name] already exists - won't create it\n";
		$GLOBALS['db_created'] = false;
	} 	else {
		echo "Creating database $_POST[db_name]\n";
		sql_query_or_die("
			CREATE DATABASE $_POST[db_name] 
			CHARACTER SET utf8");
		sql_query_or_die("SET default_storage_engine=MYISAM");
		$GLOBALS['db_created'] = true;
	}

	$db_user_quoted = quote_smart($_POST['db_user'])."@".quote_smart($_POST['db_host']);

	sql_query_or_die("CREATE USER IF NOT EXISTS $db_user_quoted IDENTIFIED BY ".quote_all($_POST['db_pass']).";");
	sql_query_or_die("GRANT ALL PRIVILEGES ON $_POST[db_name].* TO $db_user_quoted WITH GRANT OPTION");
	sql_query_or_die("GRANT ALL PRIVILEGES ON tnk.* TO $db_user_quoted WITH GRANT OPTION");
	sql_query_or_die("GRANT SESSION_VARIABLES_ADMIN ON *.* TO $db_user_quoted");
	sql_query_or_die("GRANT RELOAD ON *.* TO $db_user_quoted");

	sql_close($link); // root logs out
}

function create_db_connect_params() {
	$DONT_MAIL_JUST_LOG =  (isset($_POST['DONT_MAIL_JUST_LOG'])? "true": "false");
	$USE_HTTPS_FOR_LOGIN = (isset($_POST['USE_HTTPS_FOR_LOGIN'])? "true": "false");
	$ALTERNATIVE_SESSION_SAVE_PATH = (isset($_POST['ALTERNATIVE_SESSION_SAVE_PATH'])? "dirname(__FILE__) . '/../../../session'": "NULL");
	file_put_contents(dirname(__FILE__)."/db_connect_params.php", "<?php 
/**
 * @file parameters for db_connect.php and config.php
 * Automatically generated by $_SERVER[PHP_SELF] at $GLOBALS[current_time]
 */

\$GLOBALS['db_host'] = \$db_host = '$_POST[db_host]';
\$GLOBALS['db_user'] = \$db_user = '$_POST[db_user]';
\$GLOBALS['db_pass'] = \$db_pass = '$_POST[db_pass]';
\$GLOBALS['db_name'] = \$db_name = '$_POST[db_name]';
\$GLOBALS['db_sock'] = '$_POST[db_sock]';
\$GLOBALS['BACKUP_FILEROOT'] = str_replace('admin','_magr',dirname(__FILE__));
?".">")  /* put dirname inside the ""! */
or die ("Can't create db_connect_params");
}

function create_database_tables() {
	require_once("tables.php");
	foreach (array_keys($GLOBALS['USER_TABLES']) as $table)
		restore_table($table);
	foreach (array_keys($GLOBALS['CONFIGURATION_TABLES']) as $table)
		restore_table($table);
	sql_query_or_die("SET character_set_connection=utf8");
	sql_query_or_die("SET collation_connection=utf8_general_ci");
	sql_queries_or_die(file_get_contents(dirname(__FILE__)."/make_temporary_tables_zmnim.sql"));
	sql_queries_or_die(file_get_contents(dirname(__FILE__)."/make_temporary_tables_girsaot.sql"));
	sql_queries_or_die(file_get_contents(dirname(__FILE__)."/make_temporary_tables.sql"));
}

function create_tnk_views() {
	// from http://stackoverflow.com/a/19010747/827927
	$tnk_tables = sql_evaluate_array("SHOW TABLES FROM tnk");
	foreach ($tnk_tables as $tnk_table)
		sql_query("CREATE VIEW $tnk_table AS SELECT * FROM tnk.$tnk_table");
}

?>
