<?php
/**
 * @file combine_js_simple.php
 * combine several Javascript source files to a single file, for quicker loading.
 * A simplified version of combine_js.php, without the "minify" and "reverse direction" options.
 *
 * @example 1 
	http://server.name/combine_js.php?PARAMS
 * 
 *	Where PARAMS should contain one parameter:
 *		files=[list_of_paths_to_js_files]: list of paths from the file-root to the seperate Javascript files, without the 'js' extension.
 * and other optional parameters:
 * 		out=path from root to output file (default is to print to standard output, with text/javascript header)
 *
 * @author Erel Segal, Rent a Brain, http://tora.us.fm/rentabrain
 * @date 2007-03-05
 * 
 */

error_reporting(E_ALL);

if (!isset($_GET['files']) || !isset($_GET['out']))
	die('QUERY SYNTAX: "?files=[input files]&out=[output file]"');

$outfile = $_GET['out'];
$files = preg_split("/[+ ]/", $_GET['files']);

require_once dirname(__FILE__).'/coalesce.php';
$FILEROOT = realpath(dirname(__FILE__) . "/..");

if (!isset($_SERVER['QUERY_STRING']))
	$_SERVER['QUERY_STRING']="files=$_GET[files]&out=$outfile";

$js = '';
$js .= "var target_direction = '';\n";

print "<p>combining</p>\n";

$BAD_CHAR = "﻿";  // an invisible bad char that enters through CKEditor for some unknown reason!

foreach ($files as $file) {
	$js .= "\n\n/* $file */\n\n";
	$full_path = (preg_match("/http/", $file)? $file: "$FILEROOT/$file.js");
	$contents = file_get_contents($full_path);
 	$contents = preg_replace("|^//.*\n|m","", $contents);  // remove comments
    $js = $js . $contents;
    $bad_char_pos = strpos($js,$BAD_CHAR);
    $bad_char_warning = ($bad_char_pos!=false? "Bad char at $bad_char_pos!": "");
	print "<p>$file: ".strlen($contents)." bytes. $bad_char_warning</p>";
	$js = str_replace($BAD_CHAR, "", $js);
}


print "<p>TOTAL: ".strlen($js)." bytes</p>";

$js = "/*\nThis file was automatically generated by:\n\t$_SERVER[PHP_SELF]?$_SERVER[QUERY_STRING]\nDon't edit it directly!\n*/\n$js";

print "<p>writing to output file</p>\n";
file_put_contents("$FILEROOT/$outfile.js", $js);
echo "<p>Combined file is in $FILEROOT/$outfile.js</p>\n";
?>