/*
This file was automatically generated by:
        /_script/combine_js_simple.php?out=_script/vars&minify=0&files=_script/jquery-1.3.2.min+_script/jquery.hoverIntent.min+_script/ckeditor/ckeditor_path+_script/ckeditor/ckeditor+_script/ckeditor/ckeditor_local+_script/vars0+_script/cookies+_script/elements+_script/form_validation+_script/fields+_script/arguments+_script/sites+_script/dates/dates+_script/templates+_script/magrim+_script/search+_script/rtelang_en+_script/rte+_script/etc
Don't edit it directly!
*/