/*
This file was automatically generated by:
        /_script/combine_js.php?files=_script/jquery-1.3.2.min+_script/vars0+_script/cookies+_script/elements+_script/form_validation+_script/fields+_script/arguments+_script/sites+_script/dates/dates+_script/templates+_script/magrim+_script/search+_script/etc_prqim&out=_script/vars_prqim&minify=0
Don't edit it directly!
*/
