CREATE ALGORITHM=UNDEFINED DEFINER=`tnk1`@`localhost` SQL SECURITY DEFINER VIEW `psuqim` AS select `tnk`.`psuqim`.`id` AS `id`,`tnk`.`psuqim`.`book_code` AS `book_code`,`tnk`.`psuqim`.`book_name` AS `book_name`,`tnk`.`psuqim`.`chapter_letter` AS `chapter_letter`,`tnk`.`psuqim`.`verse_number` AS `verse_number`,`tnk`.`psuqim`.`verse_letter` AS `verse_letter`,`tnk`.`psuqim`.`text_otiot` AS `text_otiot`,`tnk`.`psuqim`.`text_maqafim` AS `text_maqafim`,`tnk`.`psuqim`.`text_niqud` AS `text_niqud`,`tnk`.`psuqim`.`text_niqud_pisuq` AS `text_niqud_pisuq`,`tnk`.`psuqim`.`text_teamim` AS `text_teamim`,`tnk`.`psuqim`.`after_text` AS `after_text`,`tnk`.`psuqim`.`ktovt_prq` AS `ktovt_prq`,`tnk`.`psuqim`.`ktovt_sikum` AS `ktovt_sikum` from `tnk`.`psuqim`;

SET character_set_database=utf8;

LOAD DATA LOCAL INFILE '$BACKUP_FILEROOT/psuqim.txt'  INTO TABLE psuqim (id,book_code,book_name,chapter_letter,verse_number,verse_letter,text_otiot,text_maqafim,text_niqud,text_niqud_pisuq,text_teamim,after_text,ktovt_prq,ktovt_sikum);

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּסַּע דֶּגֶל מַחֲנֵה בְנֵי יְהוּדָה בָּרִאשֹׁנָה לְצִבְאֹתָם; וְעַל צְבָאוֹ: נַחְשׁוֹן בֶּן עַמִּינָדָב.' WHERE `id` = 'במדי14' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 14 AND `verse_letter` = 'יד' AND `text_otiot` = 'ויסע דגל מחנה בני יהודה בראשנה לצבאתם ועל צבאו נחשון בן עמינדב' AND `text_maqafim` = 'ויסע דגל מחנה בני-יהודה בראשנה לצבאתם ועל-צבאו נחשון בן-עמינדב.' AND `text_niqud` = 'וַיִּסַּע דֶּגֶל מַחֲנֵה בְנֵי יְהוּדָה בָּרִאשֹׁנָה לְצִבְאֹתָם וְעַל צְבָאוֹ נַחְשׁוֹן בֶּן עַמִּינָדָב' AND `text_niqud_pisuq` = 'וַיִּסַּע דֶּגֶל מַחֲנֵה בְנֵי יְהוּדָה בָּרִאשֹׁנָה לְצִבְאֹתָם וְעַל צְבָאוֹ נַחְשׁוֹן בֶּן עַמִּינָדָב.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=14' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי יִשָׂשכָר: נְתַנְאֵל בֶּן צוּעָר.' WHERE `id` = 'במדי15' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 15 AND `verse_letter` = 'טו' AND `text_otiot` = 'ועל צבא מטה בני יששכר נתנאל בן צוער' AND `text_maqafim` = 'ועל-צבא מטה בני יששכר נתנאל בן-צוער.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי יִשָׂשכָר נְתַנְאֵל בֶּן צוּעָר' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי יִשָׂשכָר נְתַנְאֵל בֶּן צוּעָר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=15' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי זְבוּלֻן: אֱלִיאָב בֶּן חֵלוֹן.' WHERE `id` = 'במדי16' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 16 AND `verse_letter` = 'טז' AND `text_otiot` = 'ועל צבא מטה בני זבולן אליאב בן חלן' AND `text_maqafim` = 'ועל-צבא מטה בני זבולן אליאב בן-חלן.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי זְבוּלֻן אֱלִיאָב בֶּן חֵלוֹן' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי זְבוּלֻן אֱלִיאָב בֶּן חֵלוֹן.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=16' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהוּרַד הַמִּשְׁכָּן; וְנָסְעוּ בְנֵי גֵרְשׁוֹן וּבְנֵי מְרָרִי, נֹשְׂאֵי הַמִּשְׁכָּן.' WHERE `id` = 'במדי17' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 17 AND `verse_letter` = 'יז' AND `text_otiot` = 'והורד המשכן ונסעו בני גרשון ובני מררי נשאי המשכן' AND `text_maqafim` = 'והורד המשכן ונסעו בני-גרשון ובני מררי נשאי המשכן.' AND `text_niqud` = 'וְהוּרַד הַמִּשְׁכָּן וְנָסְעוּ בְנֵי גֵרְשׁוֹן וּבְנֵי מְרָרִי נֹשְׂאֵי הַמִּשְׁכָּן' AND `text_niqud_pisuq` = 'וְהוּרַד הַמִּשְׁכָּן וְנָסְעוּ בְנֵי גֵרְשׁוֹן וּבְנֵי מְרָרִי נֹשְׂאֵי הַמִּשְׁכָּן.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=17' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְנָסַע דֶּגֶל מַחֲנֵה רְאוּבֵן לְצִבְאֹתָם; וְעַל צְבָאוֹ: אֱלִיצוּר בֶּן שְׁדֵיאוּר.' WHERE `id` = 'במדי18' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 18 AND `verse_letter` = 'יח' AND `text_otiot` = 'ונסע דגל מחנה ראובן לצבאתם ועל צבאו אליצור בן שדיאור' AND `text_maqafim` = 'ונסע דגל מחנה ראובן לצבאתם ועל-צבאו אליצור בן-שדיאור.' AND `text_niqud` = 'וְנָסַע דֶּגֶל מַחֲנֵה רְאוּבֵן לְצִבְאֹתָם וְעַל צְבָאוֹ אֱלִיצוּר בֶּן שְׁדֵיאוּר' AND `text_niqud_pisuq` = 'וְנָסַע דֶּגֶל מַחֲנֵה רְאוּבֵן לְצִבְאֹתָם וְעַל צְבָאוֹ אֱלִיצוּר בֶּן שְׁדֵיאוּר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=18' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי שִׁמְעוֹן: שְׁלֻמִיאֵל בֶּן צוּרִישַׁדָּי.' WHERE `id` = 'במדי19' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 19 AND `verse_letter` = 'יט' AND `text_otiot` = 'ועל צבא מטה בני שמעון שלמיאל בן צורי שדי' AND `text_maqafim` = 'ועל-צבא מטה בני שמעון שלמיאל בן-צורי שדי.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי שִׁמְעוֹן שְׁלֻמִיאֵל בֶּן צוּרִי שַׁדָּי' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי שִׁמְעוֹן שְׁלֻמִיאֵל בֶּן צוּרִי שַׁדָּי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=19' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְנֵי גָד: אֶלְיָסָף בֶּן דְּעוּאֵל.' WHERE `id` = 'במדי20' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 20 AND `verse_letter` = 'כ' AND `text_otiot` = 'ועל צבא מטה בני גד אליסף בן דעואל' AND `text_maqafim` = 'ועל-צבא מטה בני-גד אליסף בן-דעואל.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְנֵי גָד אֶלְיָסָף בֶּן דְּעוּאֵל' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְנֵי גָד אֶלְיָסָף בֶּן דְּעוּאֵל.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=20' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְנָסְעוּ הַקְּהָתִים, נֹשְׂאֵי הַמִּקְדָּשׁ; וְהֵקִימוּ אֶת הַמִּשְׁכָּן, עַד בֹּאָם.' WHERE `id` = 'במדי21' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 21 AND `verse_letter` = 'כא' AND `text_otiot` = 'ונסעו הקהתים נשאי המקדש והקימו את המשכן עד באם' AND `text_maqafim` = 'ונסעו הקהתים נשאי המקדש והקימו את-המשכן עד-באם.' AND `text_niqud` = 'וְנָסְעוּ הַקְּהָתִים נֹשְׂאֵי הַמִּקְדָּשׁ וְהֵקִימוּ אֶת הַמִּשְׁכָּן עַד בֹּאָם' AND `text_niqud_pisuq` = 'וְנָסְעוּ הַקְּהָתִים נֹשְׂאֵי הַמִּקְדָּשׁ וְהֵקִימוּ אֶת הַמִּשְׁכָּן עַד בֹּאָם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=21' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי אֶפְרַיִם לְצִבְאֹתָם; וְעַל צְבָאוֹ: אֱלִישָׁמָע בֶּן עַמִּיהוּד.' WHERE `id` = 'במדי22' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 22 AND `verse_letter` = 'כב' AND `text_otiot` = 'ונסע דגל מחנה בני אפרים לצבאתם ועל צבאו אלישמע בן עמיהוד' AND `text_maqafim` = 'ונסע דגל מחנה בני-אפרים לצבאתם ועל-צבאו אלישמע בן-עמיהוד.' AND `text_niqud` = 'וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי אֶפְרַיִם לְצִבְאֹתָם וְעַל צְבָאוֹ אֱלִישָׁמָע בֶּן עַמִּיהוּד' AND `text_niqud_pisuq` = 'וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי אֶפְרַיִם לְצִבְאֹתָם וְעַל צְבָאוֹ אֱלִישָׁמָע בֶּן עַמִּיהוּד.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=22' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי מְנַשֶּׁה: גַּמְלִיאֵל בֶּן פְּדָהצוּר.' WHERE `id` = 'במדי23' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 23 AND `verse_letter` = 'כג' AND `text_otiot` = 'ועל צבא מטה בני מנשה גמליאל בן פדהצור' AND `text_maqafim` = 'ועל-צבא מטה בני מנשה גמליאל בן-פדהצור.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי מְנַשֶּׁה גַּמְלִיאֵל בֶּן פְּדָה צוּר' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי מְנַשֶּׁה גַּמְלִיאֵל בֶּן פְּדָה צוּר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=23' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי בִנְיָמִן: אֲבִידָן בֶּן גִּדְעוֹנִי.' WHERE `id` = 'במדי24' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 24 AND `verse_letter` = 'כד' AND `text_otiot` = 'ועל צבא מטה בני בנימן אבידן בן גדעוני' AND `text_maqafim` = 'ועל-צבא מטה בני בנימן אבידן בן-גדעוני.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי בִנְיָמִן אֲבִידָן בֶּן גִּדְעוֹנִי' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי בִנְיָמִן אֲבִידָן בֶּן גִּדְעוֹנִי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=24' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי דָן, מְאַסֵּף לְכָל הַמַּחֲנֹת לְצִבְאֹתָם; וְעַל צְבָאוֹ: אֲחִיעֶזֶר בֶּן עַמִּישַׁדָּי.' WHERE `id` = 'במדי25' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 25 AND `verse_letter` = 'כה' AND `text_otiot` = 'ונסע דגל מחנה בני דן מאסף לכל המחנת לצבאתם ועל צבאו אחיעזר בן עמישדי' AND `text_maqafim` = 'ונסע דגל מחנה בני-דן מאסף לכל-המחנת לצבאתם ועל-צבאו אחיעזר בן-עמישדי.' AND `text_niqud` = 'וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי דָן מְאַסֵּף לְכָל הַמַּחֲנֹת לְצִבְאֹתָם וְעַל צְבָאוֹ אֲחִיעֶזֶר בֶּן עַמִּישַׁדָּי' AND `text_niqud_pisuq` = 'וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי דָן מְאַסֵּף לְכָל הַמַּחֲנֹת לְצִבְאֹתָם וְעַל צְבָאוֹ אֲחִיעֶזֶר בֶּן עַמִּישַׁדָּי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=25' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי אָשֵׁר: פַּגְעִיאֵל בֶּן עָכְרָן.' WHERE `id` = 'במדי26' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 26 AND `verse_letter` = 'כו' AND `text_otiot` = 'ועל צבא מטה בני אשר פגעיאל בן עכרן' AND `text_maqafim` = 'ועל-צבא מטה בני אשר פגעיאל בן-עכרן.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי אָשֵׁר פַּגְעִיאֵל בֶּן עָכְרָן' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי אָשֵׁר פַּגְעִיאֵל בֶּן עָכְרָן.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=26' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי נַפְתָּלִי: אֲחִירַע בֶּן עֵינָן.' WHERE `id` = 'במדי27' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 27 AND `verse_letter` = 'כז' AND `text_otiot` = 'ועל צבא מטה בני נפתלי אחירע בן עינן' AND `text_maqafim` = 'ועל-צבא מטה בני נפתלי אחירע בן-עינן.' AND `text_niqud` = 'וְעַל צְבָא מַטֵּה בְּנֵי נַפְתָּלִי אֲחִירַע בֶּן עֵינָן' AND `text_niqud_pisuq` = 'וְעַל צְבָא מַטֵּה בְּנֵי נַפְתָּלִי אֲחִירַע בֶּן עֵינָן.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=27' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'אֵלֶּה מַסְעֵי בְנֵי-יִשְׂרָאֵל לְצִבְאֹתָם; וַיִּסָּעוּ.' WHERE `id` = 'במדי28' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 28 AND `verse_letter` = 'כח' AND `text_otiot` = 'אלה מסעי בני ישראל לצבאתם ויסעו' AND `text_maqafim` = 'אלה מסעי בני-ישראל לצבאתם ויסעו.' AND `text_niqud` = 'אֵלֶּה מַסְעֵי בְנֵי יִשְׂרָאֵל לְצִבְאֹתָם וַיִּסָּעוּ' AND `text_niqud_pisuq` = 'אֵלֶּה מַסְעֵי בְנֵי-יִשְׂרָאֵל לְצִבְאֹתָם וַיִּסָּעוּ.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=28' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר מֹשֶׁה לְחֹבָב בֶּן-רְעוּאֵל הַמִּדְיָנִי חֹתֵן מֹשֶׁה \'נֹסְעִים אֲנַחְנוּ אֶל הַמָּקוֹם אֲשֶׁר אָמַר יְהוָה \'אֹתוֹ אֶתֵּן לָכֶם\'; לְכָה אִתָּנוּ וְהֵטַבְנוּ לָךְ, כִּי יְהוָה דִּבֶּר טוֹב עַל יִשְׂרָאֵל!\'' WHERE `id` = 'במדי29' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 29 AND `verse_letter` = 'כט' AND `text_otiot` = 'ויאמר משה לחבב בן רעואל המדיני חתן משה נסעים אנחנו אל המקום אשר אמר יהוה אתו אתן לכם לכה אתנו והטבנו לך כי יהוה דבר טוב על ישראל' AND `text_maqafim` = 'ויאמר משה לחבב בן-רעואל המדיני חתן משה נסעים אנחנו אל-המקום אשר אמר יהוה אתו אתן לכם לכה אתנו והטבנו לך כי-יהוה דבר-טוב על-ישראל.' AND `text_niqud` = 'וַיֹּאמֶר מֹשֶׁה לְחֹבָב בֶּן רְעוּאֵל הַמִּדְיָנִי חֹתֵן מֹשֶׁה נֹסְעִים אֲנַחְנוּ אֶל הַמָּקוֹם אֲשֶׁר אָמַר יְהוָה אֹתוֹ אֶתֵּן לָכֶם לְכָה אִתָּנוּ וְהֵטַבְנוּ לָךְ כִּי יְהוָה דִּבֶּר טוֹב עַל יִשְׂרָאֵל' AND `text_niqud_pisuq` = 'וַיֹּאמֶר מֹשֶׁה לְחֹבָב בֶּן רְעוּאֵל הַמִּדְיָנִי חֹתֵן מֹשֶׁה נֹסְעִים אֲנַחְנוּ אֶל הַמָּקוֹם אֲשֶׁר אָמַר יְהוָה אֹתוֹ אֶתֵּן לָכֶם לְכָה אִתָּנוּ וְהֵטַבְנוּ לָךְ כִּי יְהוָה דִּבֶּר טוֹב עַל יִשְׂרָאֵל.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=29' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר אֵלָיו \'לֹא אֵלֵךְ; כִּי אִם אֶל אַרְצִי וְאֶל מוֹלַדְתִּי אֵלֵךְ.\'' WHERE `id` = 'במדי30' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 30 AND `verse_letter` = 'ל' AND `text_otiot` = 'ויאמר אליו לא אלך כי אם אל ארצי ואל מולדתי אלך' AND `text_maqafim` = 'ויאמר אליו לא אלך כי אם-אל-ארצי ואל-מולדתי אלך.' AND `text_niqud` = 'וַיֹּאמֶר אֵלָיו לֹא אֵלֵךְ כִּי אִם אֶל אַרְצִי וְאֶל מוֹלַדְתִּי אֵלֵךְ' AND `text_niqud_pisuq` = 'וַיֹּאמֶר אֵלָיו לֹא אֵלֵךְ כִּי אִם אֶל אַרְצִי וְאֶל מוֹלַדְתִּי אֵלֵךְ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=30' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר \'אַל נָא תַּעֲזֹב אֹתָנוּ; כִּי עַל כֵּן יָדַעְתָּ חֲנֹתֵנוּ בַּמִּדְבָּר, וְהָיִיתָ לָּנוּ לְעֵינָיִם.' WHERE `id` = 'במדי31' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 31 AND `verse_letter` = 'לא' AND `text_otiot` = 'ויאמר אל נא תעזב אתנו כי על כן ידעת חנתנו במדבר והיית לנו לעינים' AND `text_maqafim` = 'ויאמר אל-נא תעזב אתנו כי על-כן ידעת חנתנו במדבר והיית לנו לעינים.' AND `text_niqud` = 'וַיֹּאמֶר אַל נָא תַּעֲזֹב אֹתָנוּ כִּי עַל כֵּן יָדַעְתָּ חֲנֹתֵנוּ בַּמִּדְבָּר וְהָיִיתָ לָּנוּ לְעֵינָיִם' AND `text_niqud_pisuq` = 'וַיֹּאמֶר אַל נָא תַּעֲזֹב אֹתָנוּ כִּי עַל כֵּן יָדַעְתָּ חֲנֹתֵנוּ בַּמִּדְבָּר וְהָיִיתָ לָּנוּ לְעֵינָיִם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=31' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהָיָה כִּי תֵלֵךְ עִמָּנוּ; וְהָיָה הַטּוֹב הַהוּא, אֲשֶׁר יֵיטִיב יְהוָה עִמָּנוּ, וְהֵטַבְנוּ לָךְ.' WHERE `id` = 'במדי32' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 32 AND `verse_letter` = 'לב' AND `text_otiot` = 'והיה כי תלך עמנו והיה הטוב ההוא אשר ייטיב יהוה עמנו והטבנו לך' AND `text_maqafim` = 'והיה כי-תלך עמנו והיה הטוב ההוא אשר ייטיב יהוה עמנו והטבנו לך.' AND `text_niqud` = 'וְהָיָה כִּי תֵלֵךְ עִמָּנוּ וְהָיָה הַטּוֹב הַהוּא אֲשֶׁר יֵיטִיב יְהוָה עִמָּנוּ וְהֵטַבְנוּ לָךְ' AND `text_niqud_pisuq` = 'וְהָיָה כִּי תֵלֵךְ עִמָּנוּ וְהָיָה הַטּוֹב הַהוּא אֲשֶׁר יֵיטִיב יְהוָה עִמָּנוּ וְהֵטַבְנוּ לָךְ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=32' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּסְעוּ מֵהַר יְהוָה, דֶּרֶךְ שְׁלֹשֶׁת יָמִים; וַאֲרוֹן בְּרִית יְהוָה נֹסֵעַ לִפְנֵיהֶם, דֶּרֶךְ שְׁלֹשֶׁת יָמִים, לָתוּר לָהֶם מְנוּחָה.' WHERE `id` = 'במדי33' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 33 AND `verse_letter` = 'לג' AND `text_otiot` = 'ויסעו מהר יהוה דרך שלשת ימים וארון ברית יהוה נסע לפניהם דרך שלשת ימים לתור להם מנוחה' AND `text_maqafim` = 'ויסעו מהר יהוה דרך שלשת ימים וארון ברית-יהוה נסע לפניהם דרך שלשת ימים לתור להם מנוחה.' AND `text_niqud` = 'וַיִּסְעוּ מֵהַר יְהוָה דֶּרֶךְ שְׁלֹשֶׁת יָמִים וַאֲרוֹן בְּרִית יְהוָה נֹסֵעַ לִפְנֵיהֶם דֶּרֶךְ שְׁלֹשֶׁת יָמִים לָתוּר לָהֶם מְנוּחָה' AND `text_niqud_pisuq` = 'וַיִּסְעוּ מֵהַר יְהוָה דֶּרֶךְ שְׁלֹשֶׁת יָמִים וַאֲרוֹן בְּרִית יְהוָה נֹסֵעַ לִפְנֵיהֶם דֶּרֶךְ שְׁלֹשֶׁת יָמִים לָתוּר לָהֶם מְנוּחָה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=33' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהַחוֹנִם עָלָיו, מַטֵּה שִׁמְעוֹן; וְנָשִׂיא לִבְנֵי שִׁמְעוֹן, שְׁלֻמִיאֵל בֶּן צוּרִישַׁדָּי;' WHERE `id` = 'במדב12' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'ב' AND `verse_number` = 12 AND `verse_letter` = 'יב' AND `text_otiot` = 'והחונם עליו מטה שמעון ונשיא לבני שמעון שלמיאל בן צורי שדי' AND `text_maqafim` = 'והחונם עליו מטה שמעון ונשיא לבני שמעון שלמיאל בן-צורי-שדי.' AND `text_niqud` = 'וְהַחוֹנִם עָלָיו מַטֵּה שִׁמְעוֹן וְנָשִׂיא לִבְנֵי שִׁמְעוֹן שְׁלֻמִיאֵל בֶּן צוּרִי שַׁדָּי' AND `text_niqud_pisuq` = 'וְהַחוֹנִם עָלָיו, מַטֵּה שִׁמְעוֹן; וְנָשִׂיא לִבְנֵי שִׁמְעוֹן, שְׁלֻמִיאֵל בֶּן צוּרִי שַׁדָּי;' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0402.htm' AND `ktovt_sikum` = 'sfr=04&prq=2&psuq=12' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַעֲנַן יְהוָה עֲלֵיהֶם יוֹמָם,  בְּנָסְעָם מִן הַמַּחֲנֶה.' WHERE `id` = 'במדי34' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 34 AND `verse_letter` = 'לד' AND `text_otiot` = 'וענן יהוה עליהם יומם בנסעם מן המחנה' AND `text_maqafim` = 'וענן יהוה עליהם יומם בנסעם מן-המחנה.' AND `text_niqud` = 'וַעֲנַן יְהוָה עֲלֵיהֶם יוֹמָם בְּנָסְעָם מִן הַמַּחֲנֶה' AND `text_niqud_pisuq` = 'וַעֲנַן יְהוָה עֲלֵיהֶם יוֹמָם בְּנָסְעָם מִן הַמַּחֲנֶה.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=34' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיְהִי, בִּנְסֹעַ הָאָרֹן, וַיֹּאמֶר מֹשֶׁה \'קוּמָה יְהוָה, וְיָפֻצוּ אֹיְבֶיךָ, וְיָנֻסוּ מְשַׂנְאֶיךָ מִפָּנֶיךָ.\'' WHERE `id` = 'במדי35' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 35 AND `verse_letter` = 'לה' AND `text_otiot` = 'ויהי בנסע הארן ויאמר משה קומה יהוה ויפצו איביך וינסו משנאיך מפניך' AND `text_maqafim` = 'ויהי בנסע הארן ויאמר משה קומה יהוה ויפצו איביך וינסו משנאיך מפניך.' AND `text_niqud` = 'וַיְהִי בִּנְסֹעַ הָאָרֹן וַיֹּאמֶר מֹשֶׁה קוּמָה יְהוָה וְיָפֻצוּ אֹיְבֶיךָ וְיָנֻסוּ מְשַׂנְאֶיךָ מִפָּנֶיךָ' AND `text_niqud_pisuq` = 'וַיְהִי בִּנְסֹעַ הָאָרֹן וַיֹּאמֶר מֹשֶׁה קוּמָה יְהוָה וְיָפֻצוּ אֹיְבֶיךָ וְיָנֻסוּ מְשַׂנְאֶיךָ מִפָּנֶיךָ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=35' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וּבְנֻחֹה יֹאמַר \'שׁוּבָה יְהוָה, רִבְבוֹת אַלְפֵי יִשְׂרָאֵל.\'' WHERE `id` = 'במדי36' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'י' AND `verse_number` = 36 AND `verse_letter` = 'לו' AND `text_otiot` = 'ובנחה יאמר שובה יהוה רבבות אלפי ישראל' AND `text_maqafim` = 'ובנחה יאמר שובה יהוה רבבות אלפי ישראל.' AND `text_niqud` = 'וּבְנֻחֹה יֹאמַר שׁוּבָה יְהוָה רִבְבוֹת אַלְפֵי יִשְׂרָאֵל' AND `text_niqud_pisuq` = 'וּבְנֻחֹה יֹאמַר שׁוּבָה יְהוָה רִבְבוֹת אַלְפֵי יִשְׂרָאֵל.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0410.htm' AND `ktovt_sikum` = 'sfr=04&prq=10&psuq=36' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיְהִי הָעָם כְּמִתְאֹנְנִים, רַע בְּאָזְנֵי יְהוָה; וַיִּשְׁמַע יְהוָה וַיִּחַר אַפּוֹ, וַתִּבְעַר בָּם אֵשׁ יְהוָה, וַתֹּאכַל בִּקְצֵה הַמַּחֲנֶה.' WHERE `id` = 'במדיא1' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 1 AND `verse_letter` = 'א' AND `text_otiot` = 'ויהי העם כמתאננים רע באזני יהוה וישמע יהוה ויחר אפו ותבער בם אש יהוה ותאכל בקצה המחנה' AND `text_maqafim` = 'ויהי העם כמתאננים רע באזני יהוה וישמע יהוה ויחר אפו ותבער-בם אש יהוה ותאכל בקצה המחנה.' AND `text_niqud` = 'וַיְהִי הָעָם כְּמִתְאֹנְנִים רַע בְּאָזְנֵי יְהוָה וַיִּשְׁמַע יְהוָה וַיִּחַר אַפּוֹ וַתִּבְעַר בָּם אֵשׁ יְהוָה וַתֹּאכַל בִּקְצֵה הַמַּחֲנֶה' AND `text_niqud_pisuq` = 'וַיְהִי הָעָם כְּמִתְאֹנְנִים רַע בְּאָזְנֵי יְהוָה וַיִּשְׁמַע יְהוָה וַיִּחַר אַפּוֹ וַתִּבְעַר בָּם אֵשׁ יְהוָה וַתֹּאכַל בִּקְצֵה הַמַּחֲנֶה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=1' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּצְעַק הָעָם אֶל מֹשֶׁה; וַיִּתְפַּלֵּל מֹשֶׁה אֶל יְהוָה, וַתִּשְׁקַע הָאֵשׁ.' WHERE `id` = 'במדיא2' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 2 AND `verse_letter` = 'ב' AND `text_otiot` = 'ויצעק העם אל משה ויתפלל משה אל יהוה ותשקע האש' AND `text_maqafim` = 'ויצעק העם אל-משה ויתפלל משה אל-יהוה ותשקע האש.' AND `text_niqud` = 'וַיִּצְעַק הָעָם אֶל מֹשֶׁה וַיִּתְפַּלֵּל מֹשֶׁה אֶל יְהוָה וַתִּשְׁקַע הָאֵשׁ' AND `text_niqud_pisuq` = 'וַיִּצְעַק הָעָם אֶל מֹשֶׁה וַיִּתְפַּלֵּל מֹשֶׁה אֶל יְהוָה וַתִּשְׁקַע הָאֵשׁ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=2' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּקְרָא שֵׁם הַמָּקוֹם הַהוּא \"תַּבְעֵרָה\"; כִּי בָעֲרָה בָם אֵשׁ יְהוָה.' WHERE `id` = 'במדיא3' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 3 AND `verse_letter` = 'ג' AND `text_otiot` = 'ויקרא שם המקום ההוא תבערה כי בערה בם אש יהוה' AND `text_maqafim` = 'ויקרא שם-המקום ההוא תבערה כי-בערה בם אש יהוה.' AND `text_niqud` = 'וַיִּקְרָא שֵׁם הַמָּקוֹם הַהוּא תַּבְעֵרָה כִּי בָעֲרָה בָם אֵשׁ יְהוָה' AND `text_niqud_pisuq` = 'וַיִּקְרָא שֵׁם הַמָּקוֹם הַהוּא תַּבְעֵרָה כִּי בָעֲרָה בָם אֵשׁ יְהוָה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=3' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהָאסַפְסֻף אֲשֶׁר בְּקִרְבּוֹ, הִתְאַוּוּ תַּאֲוָה; וַיָּשֻׁבוּ וַיִּבְכּוּ גַּם בְּנֵי-יִשְׂרָאֵל, וַיֹּאמְרוּ \'מִי יַאֲכִלֵנוּ בָּשָׂר?\'' WHERE `id` = 'במדיא4' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 4 AND `verse_letter` = 'ד' AND `text_otiot` = 'והאספסף אשר בקרבו התאוו תאוה וישבו ויבכו גם בני ישראל ויאמרו מי יאכלנו בשר' AND `text_maqafim` = 'והאספסף אשר בקרבו התאוו תאוה וישבו ויבכו גם בני ישראל ויאמרו מי יאכלנו בשר.' AND `text_niqud` = 'וְהָאסַפְסֻף אֲשֶׁר בְּקִרְבּוֹ הִתְאַוּוּ תַּאֲוָה וַיָּשֻׁבוּ וַיִּבְכּוּ גַּם בְּנֵי יִשְׂרָאֵל וַיֹּאמְרוּ מִי יַאֲכִלֵנוּ בָּשָׂר' AND `text_niqud_pisuq` = 'וְהָאסַפְסֻף אֲשֶׁר בְּקִרְבּוֹ הִתְאַוּוּ תַּאֲוָה וַיָּשֻׁבוּ וַיִּבְכּוּ גַּם בְּנֵי-יִשְׂרָאֵל וַיֹּאמְרוּ מִי יַאֲכִלֵנוּ בָּשָׂר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=4' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'זָכַרְנוּ אֶת הַדָּגָה, אֲשֶׁר נֹאכַל בְּמִצְרַיִם חִנָּם; אֵת הַקִּשֻּׁאִים, וְאֵת הָאֲבַטִּחִים, וְאֶת הֶחָצִיר, וְאֶת הַבְּצָלִים, וְאֶת הַשּׁוּמִים.\'' WHERE `id` = 'במדיא5' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 5 AND `verse_letter` = 'ה' AND `text_otiot` = 'זכרנו את הדגה אשר נאכל במצרים חנם את הקשאים ואת האבטחים ואת החציר ואת הבצלים ואת השומים' AND `text_maqafim` = 'זכרנו את-הדגה אשר-נאכל במצרים חנם את הקשאים ואת האבטחים ואת-החציר ואת-הבצלים ואת-השומים.' AND `text_niqud` = 'זָכַרְנוּ אֶת הַדָּגָה אֲשֶׁר נֹאכַל בְּמִצְרַיִם חִנָּם אֵת הַקִּשֻּׁאִים וְאֵת הָאֲבַטִּחִים וְאֶת הֶחָצִיר וְאֶת הַבְּצָלִים וְאֶת הַשּׁוּמִים' AND `text_niqud_pisuq` = 'זָכַרְנוּ אֶת הַדָּגָה אֲשֶׁר נֹאכַל בְּמִצְרַיִם חִנָּם אֵת הַקִּשֻּׁאִים וְאֵת הָאֲבַטִּחִים וְאֶת הֶחָצִיר וְאֶת הַבְּצָלִים וְאֶת הַשּׁוּמִים.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=5' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וְעַתָּה נַפְשֵׁנוּ יְבֵשָׁה, אֵין כֹּל; בִּלְתִּי אֶל הַמָּן עֵינֵינוּ.\'' WHERE `id` = 'במדיא6' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 6 AND `verse_letter` = 'ו' AND `text_otiot` = 'ועתה נפשנו יבשה אין כל בלתי אל המן עינינו' AND `text_maqafim` = 'ועתה נפשנו יבשה אין כל בלתי אל-המן עינינו.' AND `text_niqud` = 'וְעַתָּה נַפְשֵׁנוּ יְבֵשָׁה אֵין כֹּל בִּלְתִּי אֶל הַמָּן עֵינֵינוּ' AND `text_niqud_pisuq` = 'וְעַתָּה נַפְשֵׁנוּ יְבֵשָׁה אֵין כֹּל בִּלְתִּי אֶל הַמָּן עֵינֵינוּ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=6' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהַמָּן, כִּזְרַע גַּד הוּא; וְעֵינוֹ, כְּעֵין הַבְּדֹלַח.' WHERE `id` = 'במדיא7' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 7 AND `verse_letter` = 'ז' AND `text_otiot` = 'והמן כזרע גד הוא ועינו כעין הבדלח' AND `text_maqafim` = 'והמן כזרע-גד הוא ועינו כעין הבדלח.' AND `text_niqud` = 'וְהַמָּן כִּזְרַע גַּד הוּא וְעֵינוֹ כְּעֵין הַבְּדֹלַח' AND `text_niqud_pisuq` = 'וְהַמָּן כִּזְרַע גַּד הוּא וְעֵינוֹ כְּעֵין הַבְּדֹלַח.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=7' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'שָׁטוּ הָעָם וְלָקְטוּ וְטָחֲנוּ בָרֵחַיִם, אוֹ דָכוּ בַּמְּדֹכָה, וּבִשְּׁלוּ בַּפָּרוּר, וְעָשׂוּ אֹתוֹ עֻגוֹת; וְהָיָה טַעְמוֹ, כְּטַעַם לְשַׁד הַשָּׁמֶן.' WHERE `id` = 'במדיא8' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 8 AND `verse_letter` = 'ח' AND `text_otiot` = 'שטו העם ולקטו וטחנו ברחים או דכו במדכה ובשלו בפרור ועשו אתו עגות והיה טעמו כטעם לשד השמן' AND `text_maqafim` = 'שטו העם ולקטו וטחנו ברחים או דכו במדכה ובשלו בפרור ועשו אתו עגות והיה טעמו כטעם לשד השמן.' AND `text_niqud` = 'שָׁטוּ הָעָם וְלָקְטוּ וְטָחֲנוּ בָרֵחַיִם אוֹ דָכוּ בַּמְּדֹכָה וּבִשְּׁלוּ בַּפָּרוּר וְעָשׂוּ אֹתוֹ עֻגוֹת וְהָיָה טַעְמוֹ כְּטַעַם לְשַׁד הַשָּׁמֶן' AND `text_niqud_pisuq` = 'שָׁטוּ הָעָם וְלָקְטוּ וְטָחֲנוּ בָרֵחַיִם אוֹ דָכוּ בַּמְּדֹכָה וּבִשְּׁלוּ בַּפָּרוּר וְעָשׂוּ אֹתוֹ עֻגוֹת וְהָיָה טַעְמוֹ כְּטַעַם לְשַׁד הַשָּׁמֶן.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=8' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וּבְרֶדֶת הַטַּל עַל הַמַּחֲנֶה לָיְלָה,  יֵרֵד הַמָּן עָלָיו.' WHERE `id` = 'במדיא9' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 9 AND `verse_letter` = 'ט' AND `text_otiot` = 'וברדת הטל על המחנה לילה ירד המן עליו' AND `text_maqafim` = 'וברדת הטל על-המחנה לילה ירד המן עליו.' AND `text_niqud` = 'וּבְרֶדֶת הַטַּל עַל הַמַּחֲנֶה לָיְלָה יֵרֵד הַמָּן עָלָיו' AND `text_niqud_pisuq` = 'וּבְרֶדֶת הַטַּל עַל הַמַּחֲנֶה לָיְלָה יֵרֵד הַמָּן עָלָיו.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=9' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּשְׁמַע מֹשֶׁה אֶת הָעָם בֹּכֶה לְמִשְׁפְּחֹתָיו, אִישׁ לְפֶתַח אָהֳלוֹ; וַיִּחַר אַף יְהוָה מְאֹד, וּבְעֵינֵי מֹשֶׁה רָע.' WHERE `id` = 'במדיא10' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 10 AND `verse_letter` = 'י' AND `text_otiot` = 'וישמע משה את העם בכה למשפחתיו איש לפתח אהלו ויחר אף יהוה מאד ובעיני משה רע' AND `text_maqafim` = 'וישמע משה את-העם בכה למשפחתיו איש לפתח אהלו ויחר-אף יהוה מאד ובעיני משה רע.' AND `text_niqud` = 'וַיִּשְׁמַע מֹשֶׁה אֶת הָעָם בֹּכֶה לְמִשְׁפְּחֹתָיו אִישׁ לְפֶתַח אָהֳלוֹ וַיִּחַר אַף יְהוָה מְאֹד וּבְעֵינֵי מֹשֶׁה רָע' AND `text_niqud_pisuq` = 'וַיִּשְׁמַע מֹשֶׁה אֶת הָעָם בֹּכֶה לְמִשְׁפְּחֹתָיו אִישׁ לְפֶתַח אָהֳלוֹ וַיִּחַר אַף יְהוָה מְאֹד וּבְעֵינֵי מֹשֶׁה רָע.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=10' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר מֹשֶׁה אֶל יְהוָה \'לָמָה הֲרֵעֹתָ לְעַבְדֶּךָ, וְלָמָּה לֹא מָצָתִי חֵן בְּעֵינֶיךָ; לָשׂוּם אֶת מַשָּׂא כָּל הָעָם הַזֶּה עָלָי?\'' WHERE `id` = 'במדיא11' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 11 AND `verse_letter` = 'יא' AND `text_otiot` = 'ויאמר משה אל יהוה למה הרעת לעבדך ולמה לא מצתי חן בעיניך לשום את משא כל העם הזה עלי' AND `text_maqafim` = 'ויאמר משה אל-יהוה למה הרעת לעבדך ולמה לא-מצתי חן בעיניך לשום את-משא כל-העם הזה עלי.' AND `text_niqud` = 'וַיֹּאמֶר מֹשֶׁה אֶל יְהוָה לָמָה הֲרֵעֹתָ לְעַבְדֶּךָ וְלָמָּה לֹא מָצָתִי חֵן בְּעֵינֶיךָ לָשׂוּם אֶת מַשָּׂא כָּל הָעָם הַזֶּה עָלָי' AND `text_niqud_pisuq` = 'וַיֹּאמֶר מֹשֶׁה אֶל יְהוָה לָמָה הֲרֵעֹתָ לְעַבְדֶּךָ וְלָמָּה לֹא מָצָתִי חֵן בְּעֵינֶיךָ לָשׂוּם אֶת מַשָּׂא כָּל הָעָם הַזֶּה עָלָי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=11' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'הֶאָנֹכִי הָרִיתִי אֵת כָּל הָעָם הַזֶּה, אִם אָנֹכִי יְלִדְתִּיהוּ? כִּי תֹאמַר אֵלַי \'שָׂאֵהוּ בְחֵיקֶךָ כַּאֲשֶׁר יִשָּׂא הָאֹמֵן אֶת הַיֹּנֵק\', עַל הָאֲדָמָה אֲשֶׁר נִשְׁבַּעְתָּ לַאֲבֹתָיו!\'' WHERE `id` = 'במדיא12' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 12 AND `verse_letter` = 'יב' AND `text_otiot` = 'האנכי הריתי את כל העם הזה אם אנכי ילדתיהו כי תאמר אלי שאהו בחיקך כאשר ישא האמן את הינק על האדמה אשר נשבעת לאבתיו' AND `text_maqafim` = 'האנכי הריתי את כל-העם הזה אם-אנכי ילדתיהו כי-תאמר אלי שאהו בחיקך כאשר ישא האמן את-הינק על האדמה אשר נשבעת לאבתיו.' AND `text_niqud` = 'הֶאָנֹכִי הָרִיתִי אֵת כָּל הָעָם הַזֶּה אִם אָנֹכִי יְלִדְתִּיהוּ כִּי תֹאמַר אֵלַי שָׂאֵהוּ בְחֵיקֶךָ כַּאֲשֶׁר יִשָּׂא הָאֹמֵן אֶת הַיֹּנֵק עַל הָאֲדָמָה אֲשֶׁר נִשְׁבַּעְתָּ לַאֲבֹתָיו' AND `text_niqud_pisuq` = 'הֶאָנֹכִי הָרִיתִי אֵת כָּל הָעָם הַזֶּה אִם אָנֹכִי יְלִדְתִּיהוּ כִּי תֹאמַר אֵלַי שָׂאֵהוּ בְחֵיקֶךָ כַּאֲשֶׁר יִשָּׂא הָאֹמֵן אֶת הַיֹּנֵק עַל הָאֲדָמָה אֲשֶׁר נִשְׁבַּעְתָּ לַאֲבֹתָיו.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=12' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'מֵאַיִן לִי בָּשָׂר לָתֵת לְכָל הָעָם הַזֶּה? כִּי יִבְכּוּ עָלַי לֵאמֹר \'תְּנָה לָּנוּ בָשָׂר וְנֹאכֵלָה!\'\'' WHERE `id` = 'במדיא13' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 13 AND `verse_letter` = 'יג' AND `text_otiot` = 'מאין לי בשר לתת לכל העם הזה כי יבכו עלי לאמר תנה לנו בשר ונאכלה' AND `text_maqafim` = 'מאין לי בשר לתת לכל-העם הזה כי-יבכו עלי לאמר תנה-לנו בשר ונאכלה.' AND `text_niqud` = 'מֵאַיִן לִי בָּשָׂר לָתֵת לְכָל הָעָם הַזֶּה כִּי יִבְכּוּ עָלַי לֵאמֹר תְּנָה לָּנוּ בָשָׂר וְנֹאכֵלָה' AND `text_niqud_pisuq` = 'מֵאַיִן לִי בָּשָׂר לָתֵת לְכָל הָעָם הַזֶּה כִּי יִבְכּוּ עָלַי לֵאמֹר תְּנָה לָּנוּ בָשָׂר וְנֹאכֵלָה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=13' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'לֹא אוּכַל אָנֹכִי לְבַדִּי לָשֵׂאת אֶת כָּל הָעָם הַזֶּה; כִּי כָבֵד מִמֶּנִּי.\'' WHERE `id` = 'במדיא14' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 14 AND `verse_letter` = 'יד' AND `text_otiot` = 'לא אוכל אנכי לבדי לשאת את כל העם הזה כי כבד ממני' AND `text_maqafim` = 'לא-אוכל אנכי לבדי לשאת את-כל-העם הזה כי כבד ממני.' AND `text_niqud` = 'לֹא אוּכַל אָנֹכִי לְבַדִּי לָשֵׂאת אֶת כָּל הָעָם הַזֶּה כִּי כָבֵד מִמֶּנִּי' AND `text_niqud_pisuq` = 'לֹא אוּכַל אָנֹכִי לְבַדִּי לָשֵׂאת אֶת כָּל הָעָם הַזֶּה כִּי כָבֵד מִמֶּנִּי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=14' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וְאִם כָּכָה אַתְּ עֹשֶׂה לִּי, הָרְגֵנִי נָא הָרֹג, אִם מָצָאתִי חֵן בְּעֵינֶיךָ; וְאַל אֶרְאֶה בְּרָעָתִי.\'' WHERE `id` = 'במדיא15' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 15 AND `verse_letter` = 'טו' AND `text_otiot` = 'ואם ככה את עשה לי הרגני נא הרג אם מצאתי חן בעיניך ואל אראה ברעתי' AND `text_maqafim` = 'ואם-ככה את-עשה לי הרגני נא הרג אם-מצאתי חן בעיניך ואל-אראה ברעתי.' AND `text_niqud` = 'וְאִם כָּכָה אַתְּ עֹשֶׂה לִּי הָרְגֵנִי נָא הָרֹג אִם מָצָאתִי חֵן בְּעֵינֶיךָ וְאַל אֶרְאֶה בְּרָעָתִי' AND `text_niqud_pisuq` = 'וְאִם כָּכָה אַתְּ עֹשֶׂה לִּי הָרְגֵנִי נָא הָרֹג אִם מָצָאתִי חֵן בְּעֵינֶיךָ וְאַל אֶרְאֶה בְּרָעָתִי.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=15' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה \'אֶסְפָה לִּי שִׁבְעִים אִישׁ מִזִּקְנֵי יִשְׂרָאֵל; אֲשֶׁר יָדַעְתָּ, כִּי הֵם זִקְנֵי הָעָם וְשֹׁטְרָיו; וְלָקַחְתָּ אֹתָם אֶל אֹהֶל מוֹעֵד, וְהִתְיַצְּבוּ שָׁם עִמָּךְ.\'' WHERE `id` = 'במדיא16' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 16 AND `verse_letter` = 'טז' AND `text_otiot` = 'ויאמר יהוה אל משה אספה לי שבעים איש מזקני ישראל אשר ידעת כי הם זקני העם ושטריו ולקחת אתם אל אהל מועד והתיצבו שם עמך' AND `text_maqafim` = 'ויאמר יהוה אל-משה אספה-לי שבעים איש מזקני ישראל אשר ידעת כי-הם זקני העם ושטריו ולקחת אתם אל-אהל מועד והתיצבו שם עמך.' AND `text_niqud` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה אֶסְפָה לִּי שִׁבְעִים אִישׁ מִזִּקְנֵי יִשְׂרָאֵל אֲשֶׁר יָדַעְתָּ כִּי הֵם זִקְנֵי הָעָם וְשֹׁטְרָיו וְלָקַחְתָּ אֹתָם אֶל אֹהֶל מוֹעֵד וְהִתְיַצְּבוּ שָׁם עִמָּךְ' AND `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה אֶסְפָה לִּי שִׁבְעִים אִישׁ מִזִּקְנֵי יִשְׂרָאֵל אֲשֶׁר יָדַעְתָּ כִּי הֵם זִקְנֵי הָעָם וְשֹׁטְרָיו וְלָקַחְתָּ אֹתָם אֶל אֹהֶל מוֹעֵד וְהִתְיַצְּבוּ שָׁם עִמָּךְ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=16' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וְיָרַדְתִּי, וְדִבַּרְתִּי עִמְּךָ שָׁם; וְאָצַלְתִּי מִן הָרוּחַ אֲשֶׁר עָלֶיךָ, וְשַׂמְתִּי עֲלֵיהֶם; וְנָשְׂאוּ אִתְּךָ בְּמַשָּׂא הָעָם, וְלֹא תִשָּׂא אַתָּה לְבַדֶּךָ.\'' WHERE `id` = 'במדיא17' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 17 AND `verse_letter` = 'יז' AND `text_otiot` = 'וירדתי ודברתי עמך שם ואצלתי מן הרוח אשר עליך ושמתי עליהם ונשאו אתך במשא העם ולא תשא אתה לבדך' AND `text_maqafim` = 'וירדתי ודברתי עמך שם ואצלתי מן-הרוח אשר עליך ושמתי עליהם ונשאו אתך במשא העם ולא-תשא אתה לבדך.' AND `text_niqud` = 'וְיָרַדְתִּי וְדִבַּרְתִּי עִמְּךָ שָׁם וְאָצַלְתִּי מִן הָרוּחַ אֲשֶׁר עָלֶיךָ וְשַׂמְתִּי עֲלֵיהֶם וְנָשְׂאוּ אִתְּךָ בְּמַשָּׂא הָעָם וְלֹא תִשָּׂא אַתָּה לְבַדֶּךָ' AND `text_niqud_pisuq` = 'וְיָרַדְתִּי וְדִבַּרְתִּי עִמְּךָ שָׁם וְאָצַלְתִּי מִן הָרוּחַ אֲשֶׁר עָלֶיךָ וְשַׂמְתִּי עֲלֵיהֶם וְנָשְׂאוּ אִתְּךָ בְּמַשָּׂא הָעָם וְלֹא תִשָּׂא אַתָּה לְבַדֶּךָ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=17' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וְאֶל הָעָם תֹּאמַר \'הִתְקַדְּשׁוּ לְמָחָר וַאֲכַלְתֶּם בָּשָׂר; כִּי בְּכִיתֶם בְּאָזְנֵי יְהוָה לֵאמֹר \'מִי יַאֲכִלֵנוּ בָּשָׂר, כִּי טוֹב לָנוּ בְּמִצְרָיִם?\' וְנָתַן יְהוָה לָכֶם בָּשָׂר, וַאֲכַלְתֶּם.\'\'' WHERE `id` = 'במדיא18' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 18 AND `verse_letter` = 'יח' AND `text_otiot` = 'ואל העם תאמר התקדשו למחר ואכלתם בשר כי בכיתם באזני יהוה לאמר מי יאכלנו בשר כי טוב לנו במצרים ונתן יהוה לכם בשר ואכלתם' AND `text_maqafim` = 'ואל-העם תאמר התקדשו למחר ואכלתם בשר כי בכיתם באזני יהוה לאמר מי יאכלנו בשר כי-טוב לנו במצרים ונתן יהוה לכם בשר ואכלתם.' AND `text_niqud` = 'וְאֶל הָעָם תֹּאמַר הִתְקַדְּשׁוּ לְמָחָר וַאֲכַלְתֶּם בָּשָׂר כִּי בְּכִיתֶם בְּאָזְנֵי יְהוָה לֵאמֹר מִי יַאֲכִלֵנוּ בָּשָׂר כִּי טוֹב לָנוּ בְּמִצְרָיִם וְנָתַן יְהוָה לָכֶם בָּשָׂר וַאֲכַלְתֶּם' AND `text_niqud_pisuq` = 'וְאֶל הָעָם תֹּאמַר הִתְקַדְּשׁוּ לְמָחָר וַאֲכַלְתֶּם בָּשָׂר כִּי בְּכִיתֶם בְּאָזְנֵי יְהוָה לֵאמֹר מִי יַאֲכִלֵנוּ בָּשָׂר כִּי טוֹב לָנוּ בְּמִצְרָיִם וְנָתַן יְהוָה לָכֶם בָּשָׂר וַאֲכַלְתֶּם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=18' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'\'לֹא יוֹם אֶחָד תֹּאכְלוּן, וְלֹא יוֹמָיִם; וְלֹא חֲמִשָּׁה יָמִים, וְלֹא עֲשָׂרָה יָמִים, וְלֹא עֶשְׂרִים יוֹם.\'\'' WHERE `id` = 'במדיא19' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 19 AND `verse_letter` = 'יט' AND `text_otiot` = 'לא יום אחד תאכלון ולא יומים ולא חמשה ימים ולא עשרה ימים ולא עשרים יום' AND `text_maqafim` = 'לא יום אחד תאכלון ולא יומים ולא חמשה ימים ולא עשרה ימים ולא עשרים יום.' AND `text_niqud` = 'לֹא יוֹם אֶחָד תֹּאכְלוּן וְלֹא יוֹמָיִם וְלֹא חֲמִשָּׁה יָמִים וְלֹא עֲשָׂרָה יָמִים וְלֹא עֶשְׂרִים יוֹם' AND `text_niqud_pisuq` = 'לֹא יוֹם אֶחָד תֹּאכְלוּן וְלֹא יוֹמָיִם וְלֹא חֲמִשָּׁה יָמִים וְלֹא עֲשָׂרָה יָמִים וְלֹא עֶשְׂרִים יוֹם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=19' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'\'עַד חֹדֶשׁ יָמִים, עַד אֲשֶׁר יֵצֵא מֵאַפְּכֶם, וְהָיָה לָכֶם לְזָרָא; יַעַן כִּי מְאַסְתֶּם אֶת יְהוָה אֲשֶׁר בְּקִרְבְּכֶם, וַתִּבְכּוּ לְפָנָיו לֵאמֹר \'לָמָּה זֶּה יָצָאנוּ מִמִּצְרָיִם?\'\'\'.' WHERE `id` = 'במדיא20' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 20 AND `verse_letter` = 'כ' AND `text_otiot` = 'עד חדש ימים עד אשר יצא מאפכם והיה לכם לזרא יען כי מאסתם את יהוה אשר בקרבכם ותבכו לפניו לאמר למה זה יצאנו ממצרים' AND `text_maqafim` = 'עד חדש ימים עד אשר-יצא מאפכם והיה לכם לזרא יען כי-מאסתם את-יהוה אשר בקרבכם ותבכו לפניו לאמר למה זה יצאנו ממצרים.' AND `text_niqud` = 'עַד חֹדֶשׁ יָמִים עַד אֲשֶׁר יֵצֵא מֵאַפְּכֶם וְהָיָה לָכֶם לְזָרָא יַעַן כִּי מְאַסְתֶּם אֶת יְהוָה אֲשֶׁר בְּקִרְבְּכֶם וַתִּבְכּוּ לְפָנָיו לֵאמֹר לָמָּה זֶּה יָצָאנוּ מִמִּצְרָיִם' AND `text_niqud_pisuq` = 'עַד חֹדֶשׁ יָמִים עַד אֲשֶׁר יֵצֵא מֵאַפְּכֶם וְהָיָה לָכֶם לְזָרָא יַעַן כִּי מְאַסְתֶּם אֶת יְהוָה אֲשֶׁר בְּקִרְבְּכֶם וַתִּבְכּוּ לְפָנָיו לֵאמֹר לָמָּה זֶּה יָצָאנוּ מִמִּצְרָיִם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=20' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר מֹשֶׁה \'שֵׁשׁ-מֵאוֹת אֶלֶף רַגְלִי, הָעָם אֲשֶׁר אָנֹכִי בְּקִרְבּוֹ; וְאַתָּה אָמַרְתָּ \'בָּשָׂר אֶתֵּן לָהֶם, וְאָכְלוּ חֹדֶשׁ יָמִים\';\'' WHERE `id` = 'במדיא21' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 21 AND `verse_letter` = 'כא' AND `text_otiot` = 'ויאמר משה שש מאות אלף רגלי העם אשר אנכי בקרבו ואתה אמרת בשר אתן להם ואכלו חדש ימים' AND `text_maqafim` = 'ויאמר משה שש-מאות אלף רגלי העם אשר אנכי בקרבו ואתה אמרת בשר אתן להם ואכלו חדש ימים.' AND `text_niqud` = 'וַיֹּאמֶר מֹשֶׁה שֵׁשׁ מֵאוֹת אֶלֶף רַגְלִי הָעָם אֲשֶׁר אָנֹכִי בְּקִרְבּוֹ וְאַתָּה אָמַרְתָּ בָּשָׂר אֶתֵּן לָהֶם וְאָכְלוּ חֹדֶשׁ יָמִים' AND `text_niqud_pisuq` = 'וַיֹּאמֶר מֹשֶׁה שֵׁשׁ מֵאוֹת אֶלֶף רַגְלִי הָעָם אֲשֶׁר אָנֹכִי בְּקִרְבּוֹ וְאַתָּה אָמַרְתָּ בָּשָׂר אֶתֵּן לָהֶם וְאָכְלוּ חֹדֶשׁ יָמִים.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=21' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'- הֲצֹאן וּבָקָר יִשָּׁחֵט לָהֶם, וּמָצָא לָהֶם? אִם אֶת כָּל דְּגֵי הַיָּם יֵאָסֵף לָהֶם, וּמָצָא לָהֶם?\'' WHERE `id` = 'במדיא22' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 22 AND `verse_letter` = 'כב' AND `text_otiot` = 'הצאן ובקר ישחט להם ומצא להם אם את כל דגי הים יאסף להם ומצא להם' AND `text_maqafim` = 'הצאן ובקר ישחט להם ומצא להם אם את-כל-דגי הים יאסף להם ומצא להם.' AND `text_niqud` = 'הֲצֹאן וּבָקָר יִשָּׁחֵט לָהֶם וּמָצָא לָהֶם אִם אֶת כָּל דְּגֵי הַיָּם יֵאָסֵף לָהֶם וּמָצָא לָהֶם' AND `text_niqud_pisuq` = 'הֲצֹאן וּבָקָר יִשָּׁחֵט לָהֶם וּמָצָא לָהֶם אִם אֶת כָּל דְּגֵי הַיָּם יֵאָסֵף לָהֶם וּמָצָא לָהֶם.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=22' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה \'הֲיַד יְהוָה תִּקְצָר? עַתָּה תִרְאֶה הֲיִקְרְךָ דְבָרִי אִם לֹא.\'' WHERE `id` = 'במדיא23' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 23 AND `verse_letter` = 'כג' AND `text_otiot` = 'ויאמר יהוה אל משה היד יהוה תקצר עתה תראה היקרך דברי אם לא' AND `text_maqafim` = 'ויאמר יהוה אל-משה היד יהוה תקצר עתה תראה היקרך דברי אם-לא.' AND `text_niqud` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה הֲיַד יְהוָה תִּקְצָר עַתָּה תִרְאֶה הֲיִקְרְךָ דְבָרִי אִם לֹא' AND `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה הֲיַד יְהוָה תִּקְצָר עַתָּה תִרְאֶה הֲיִקְרְךָ דְבָרִי אִם לֹא.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=23' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֵּצֵא מֹשֶׁה, וַיְדַבֵּר אֶל הָעָם, אֵת דִּבְרֵי יְהוָה; וַיֶּאֱסֹף שִׁבְעִים אִישׁ מִזִּקְנֵי הָעָם, וַיַּעֲמֵד אֹתָם סְבִיבֹת הָאֹהֶל.' WHERE `id` = 'במדיא24' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 24 AND `verse_letter` = 'כד' AND `text_otiot` = 'ויצא משה וידבר אל העם את דברי יהוה ויאסף שבעים איש מזקני העם ויעמד אתם סביבת האהל' AND `text_maqafim` = 'ויצא משה וידבר אל-העם את דברי יהוה ויאסף שבעים איש מזקני העם ויעמד אתם סביבת האהל.' AND `text_niqud` = 'וַיֵּצֵא מֹשֶׁה וַיְדַבֵּר אֶל הָעָם אֵת דִּבְרֵי יְהוָה וַיֶּאֱסֹף שִׁבְעִים אִישׁ מִזִּקְנֵי הָעָם וַיַּעֲמֵד אֹתָם סְבִיבֹת הָאֹהֶל' AND `text_niqud_pisuq` = 'וַיֵּצֵא מֹשֶׁה וַיְדַבֵּר אֶל הָעָם אֵת דִּבְרֵי יְהוָה וַיֶּאֱסֹף שִׁבְעִים אִישׁ מִזִּקְנֵי הָעָם וַיַּעֲמֵד אֹתָם סְבִיבֹת הָאֹהֶל.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=24' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֵּרֶד יְהוָה בֶּעָנָן, וַיְדַבֵּר אֵלָיו; וַיָּאצֶל מִן הָרוּחַ אֲשֶׁר עָלָיו, וַיִּתֵּן עַל שִׁבְעִים אִישׁ הַזְּקֵנִים; וַיְהִי כְּנוֹחַ עֲלֵיהֶם הָרוּחַ, וַיִּתְנַבְּאוּ וְלֹא יָסָפוּ.' WHERE `id` = 'במדיא25' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 25 AND `verse_letter` = 'כה' AND `text_otiot` = 'וירד יהוה בענן וידבר אליו ויאצל מן הרוח אשר עליו ויתן על שבעים איש הזקנים ויהי כנוח עליהם הרוח ויתנבאו ולא יספו' AND `text_maqafim` = 'וירד יהוה בענן וידבר אליו ויאצל מן-הרוח אשר עליו ויתן על-שבעים איש הזקנים ויהי כנוח עליהם הרוח ויתנבאו ולא יספו.' AND `text_niqud` = 'וַיֵּרֶד יְהוָה בֶּעָנָן וַיְדַבֵּר אֵלָיו וַיָּאצֶל מִן הָרוּחַ אֲשֶׁר עָלָיו וַיִּתֵּן עַל שִׁבְעִים אִישׁ הַזְּקֵנִים וַיְהִי כְּנוֹחַ עֲלֵיהֶם הָרוּחַ וַיִּתְנַבְּאוּ וְלֹא יָסָפוּ' AND `text_niqud_pisuq` = 'וַיֵּרֶד יְהוָה בֶּעָנָן וַיְדַבֵּר אֵלָיו וַיָּאצֶל מִן הָרוּחַ אֲשֶׁר עָלָיו וַיִּתֵּן עַל שִׁבְעִים אִישׁ הַזְּקֵנִים וַיְהִי כְּנוֹחַ עֲלֵיהֶם הָרוּחַ וַיִּתְנַבְּאוּ וְלֹא יָסָפוּ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=25' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּשָּׁאֲרוּ שְׁנֵי אֲנָשִׁים בַּמַּחֲנֶה: שֵׁם הָאֶחָד אֶלְדָּד, וְשֵׁם הַשֵּׁנִי מֵידָד; וַתָּנַח עֲלֵיהֶם הָרוּחַ, וְהֵמָּה בַּכְּתֻבִים, וְלֹא יָצְאוּ הָאֹהֱלָה; וַיִּתְנַבְּאוּ בַּמַּחֲנֶה. *' WHERE `id` = 'במדיא26' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 26 AND `verse_letter` = 'כו' AND `text_otiot` = 'וישארו שני אנשים במחנה שם האחד אלדד ושם השני מידד ותנח עלהם הרוח והמה בכתבים ולא יצאו האהלה ויתנבאו במחנה' AND `text_maqafim` = 'וישארו שני-אנשים במחנה שם האחד אלדד ושם השני מידד ותנח עלהם הרוח והמה בכתבים ולא יצאו האהלה ויתנבאו במחנה.' AND `text_niqud` = 'וַיִּשָּׁאֲרוּ שְׁנֵי אֲנָשִׁים בַּמַּחֲנֶה שֵׁם הָאֶחָד אֶלְדָּד וְשֵׁם הַשֵּׁנִי מֵידָד וַתָּנַח עֲלֵיהֶם הָרוּחַ וְהֵמָּה בַּכְּתֻבִים וְלֹא יָצְאוּ הָאֹהֱלָה וַיִּתְנַבְּאוּ בַּמַּחֲנֶה' AND `text_niqud_pisuq` = 'וַיִּשָּׁאֲרוּ שְׁנֵי אֲנָשִׁים בַּמַּחֲנֶה שֵׁם הָאֶחָד אֶלְדָּד וְשֵׁם הַשֵּׁנִי מֵידָד וַתָּנַח עֲלֵיהֶם הָרוּחַ וְהֵמָּה בַּכְּתֻבִים וְלֹא יָצְאוּ הָאֹהֱלָה וַיִּתְנַבְּאוּ בַּמַּחֲנֶה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=26' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיָּרָץ הַנַּעַר, וַיַּגֵּד לְמֹשֶׁה, וַיֹּאמַר \'אֶלְדָּד וּמֵידָד, מִתְנַבְּאִים בַּמַּחֲנֶה!\'' WHERE `id` = 'במדיא27' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 27 AND `verse_letter` = 'כז' AND `text_otiot` = 'וירץ הנער ויגד למשה ויאמר אלדד ומידד מתנבאים במחנה' AND `text_maqafim` = 'וירץ הנער ויגד למשה ויאמר אלדד ומידד מתנבאים במחנה.' AND `text_niqud` = 'וַיָּרָץ הַנַּעַר וַיַּגֵּד לְמֹשֶׁה וַיֹּאמַר אֶלְדָּד וּמֵידָד מִתְנַבְּאִים בַּמַּחֲנֶה' AND `text_niqud_pisuq` = 'וַיָּרָץ הַנַּעַר וַיַּגֵּד לְמֹשֶׁה וַיֹּאמַר אֶלְדָּד וּמֵידָד מִתְנַבְּאִים בַּמַּחֲנֶה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=27' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיַּעַן יְהוֹשֻׁעַ בִּן-נוּן, מְשָׁרֵת מֹשֶׁה מִבְּחֻרָיו, וַיֹּאמַר \'אֲדֹנִי מֹשֶׁה, כְּלָאֵם!\'' WHERE `id` = 'במדיא28' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 28 AND `verse_letter` = 'כח' AND `text_otiot` = 'ויען יהושע בן נון משרת משה מבחריו ויאמר אדני משה כלאם' AND `text_maqafim` = 'ויען יהושע בן-נון משרת משה מבחריו ויאמר אדני משה כלאם.' AND `text_niqud` = 'וַיַּעַן יְהוֹשֻׁעַ בִּן נוּן מְשָׁרֵת מֹשֶׁה מִבְּחֻרָיו וַיֹּאמַר אֲדֹנִי מֹשֶׁה כְּלָאֵם' AND `text_niqud_pisuq` = 'וַיַּעַן יְהוֹשֻׁעַ בִּן-נוּן מְשָׁרֵת מֹשֶׁה מִבְּחֻרָיו וַיֹּאמַר אֲדֹנִי מֹשֶׁה כְּלָאֵם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=28' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר לוֹ מֹשֶׁה \'הַמְקַנֵּא אַתָּה לִי? וּמִי יִתֵּן כָּל עַם יְהוָה נְבִיאִים, כִּי יִתֵּן יְהוָה אֶת רוּחוֹ עֲלֵיהֶם!\'' WHERE `id` = 'במדיא29' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 29 AND `verse_letter` = 'כט' AND `text_otiot` = 'ויאמר לו משה המקנא אתה לי ומי יתן כל עם יהוה נביאים כי יתן יהוה את רוחו עליהם' AND `text_maqafim` = 'ויאמר לו משה המקנא אתה לי ומי יתן כל-עם יהוה נביאים כי-יתן יהוה את-רוחו עליהם.' AND `text_niqud` = 'וַיֹּאמֶר לוֹ מֹשֶׁה הַמְקַנֵּא אַתָּה לִי וּמִי יִתֵּן כָּל עַם יְהוָה נְבִיאִים כִּי יִתֵּן יְהוָה אֶת רוּחוֹ עֲלֵיהֶם' AND `text_niqud_pisuq` = 'וַיֹּאמֶר לוֹ מֹשֶׁה הַמְקַנֵּא אַתָּה לִי וּמִי יִתֵּן כָּל עַם יְהוָה נְבִיאִים כִּי יִתֵּן יְהוָה אֶת רוּחוֹ עֲלֵיהֶם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=29' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֵּאָסֵף מֹשֶׁה אֶל הַמַּחֲנֶה; הוּא וְזִקְנֵי יִשְׂרָאֵל.' WHERE `id` = 'במדיא30' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 30 AND `verse_letter` = 'ל' AND `text_otiot` = 'ויאסף משה אל המחנה הוא וזקני ישראל' AND `text_maqafim` = 'ויאסף משה אל-המחנה הוא וזקני ישראל.' AND `text_niqud` = 'וַיֵּאָסֵף מֹשֶׁה אֶל הַמַּחֲנֶה הוּא וְזִקְנֵי יִשְׂרָאֵל' AND `text_niqud_pisuq` = 'וַיֵּאָסֵף מֹשֶׁה אֶל הַמַּחֲנֶה הוּא וְזִקְנֵי יִשְׂרָאֵל.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=30' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְרוּחַ נָסַע מֵאֵת יְהוָה, וַיָּגָז שַׂלְוִים מִן הַיָּם; וַיִּטֹּשׁ עַל הַמַּחֲנֶה כְּדֶרֶךְ יוֹם כֹּה וּכְדֶרֶךְ יוֹם כֹּה, סְבִיבוֹת הַמַּחֲנֶה; וּכְאַמָּתַיִם עַל פְּנֵי הָאָרֶץ.' WHERE `id` = 'במדיא31' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 31 AND `verse_letter` = 'לא' AND `text_otiot` = 'ורוח נסע מאת יהוה ויגז שלוים מן הים ויטש על המחנה כדרך יום כה וכדרך יום כה סביבות המחנה וכאמתים על פני הארץ' AND `text_maqafim` = 'ורוח נסע מאת יהוה ויגז שלוים מן-הים ויטש על-המחנה כדרך יום כה וכדרך יום כה סביבות המחנה וכאמתים על-פני הארץ.' AND `text_niqud` = 'וְרוּחַ נָסַע מֵאֵת יְהוָה וַיָּגָז שַׂלְוִים מִן הַיָּם וַיִּטֹּשׁ עַל הַמַּחֲנֶה כְּדֶרֶךְ יוֹם כֹּה וּכְדֶרֶךְ יוֹם כֹּה סְבִיבוֹת הַמַּחֲנֶה וּכְאַמָּתַיִם עַל פְּנֵי הָאָרֶץ' AND `text_niqud_pisuq` = 'וְרוּחַ נָסַע מֵאֵת יְהוָה וַיָּגָז שַׂלְוִים מִן הַיָּם וַיִּטֹּשׁ עַל הַמַּחֲנֶה כְּדֶרֶךְ יוֹם כֹּה וּכְדֶרֶךְ יוֹם כֹּה סְבִיבוֹת הַמַּחֲנֶה וּכְאַמָּתַיִם עַל פְּנֵי הָאָרֶץ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=31' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיָּקָם הָעָם כָּל הַיּוֹם הַהוּא וְכָל הַלַּיְלָה וְכֹל יוֹם הַמָּחֳרָת, וַיַּאַסְפוּ אֶת הַשְּׂלָו, הַמַּמְעִיט  אָסַף עֲשָׂרָה חֳמָרִים; וַיִּשְׁטְחוּ לָהֶם שָׁטוֹחַ, סְבִיבוֹת הַמַּחֲנֶה.' WHERE `id` = 'במדיא32' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 32 AND `verse_letter` = 'לב' AND `text_otiot` = 'ויקם העם כל היום ההוא וכל הלילה וכל יום המחרת ויאספו את השלו הממעיט אסף עשרה חמרים וישטחו להם שטוח סביבות המחנה' AND `text_maqafim` = 'ויקם העם כל-היום ההוא וכל-הלילה וכל יום המחרת ויאספו את-השלו הממעיט אסף עשרה חמרים וישטחו להם שטוח סביבות המחנה.' AND `text_niqud` = 'וַיָּקָם הָעָם כָּל הַיּוֹם הַהוּא וְכָל הַלַּיְלָה וְכֹל יוֹם הַמָּחֳרָת וַיַּאַסְפוּ אֶת הַשְּׂלָו הַמַּמְעִיט אָסַף עֲשָׂרָה חֳמָרִים וַיִּשְׁטְחוּ לָהֶם שָׁטוֹחַ סְבִיבוֹת הַמַּחֲנֶה' AND `text_niqud_pisuq` = 'וַיָּקָם הָעָם כָּל הַיּוֹם הַהוּא וְכָל הַלַּיְלָה וְכֹל יוֹם הַמָּחֳרָת וַיַּאַסְפוּ אֶת הַשְּׂלָו הַמַּמְעִיט אָסַף עֲשָׂרָה חֳמָרִים וַיִּשְׁטְחוּ לָהֶם שָׁטוֹחַ סְבִיבוֹת הַמַּחֲנֶה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=32' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'הַבָּשָׂר עוֹדֶנּוּ בֵּין שִׁנֵּיהֶם, טֶרֶם יִכָּרֵת; וְאַף יְהוָה חָרָה בָעָם, וַיַּךְ יְהוָה בָּעָם, מַכָּה רַבָּה מְאֹד.' WHERE `id` = 'במדיא33' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 33 AND `verse_letter` = 'לג' AND `text_otiot` = 'הבשר עודנו בין שניהם טרם יכרת ואף יהוה חרה בעם ויך יהוה בעם מכה רבה מאד' AND `text_maqafim` = 'הבשר עודנו בין שניהם טרם יכרת ואף יהוה חרה בעם ויך יהוה בעם מכה רבה מאד.' AND `text_niqud` = 'הַבָּשָׂר עוֹדֶנּוּ בֵּין שִׁנֵּיהֶם טֶרֶם יִכָּרֵת וְאַף יְהוָה חָרָה בָעָם וַיַּךְ יְהוָה בָּעָם מַכָּה רַבָּה מְאֹד' AND `text_niqud_pisuq` = 'הַבָּשָׂר עוֹדֶנּוּ בֵּין שִׁנֵּיהֶם טֶרֶם יִכָּרֵת וְאַף יְהוָה חָרָה בָעָם וַיַּךְ יְהוָה בָּעָם מַכָּה רַבָּה מְאֹד.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=33' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּקְרָא אֶת שֵׁם הַמָּקוֹם הַהוּא \"קִבְרוֹת הַתַּאֲוָה\"; כִּי שָׁם קָבְרוּ, אֶת הָעָם הַמִּתְאַוִּים.' WHERE `id` = 'במדיא34' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 34 AND `verse_letter` = 'לד' AND `text_otiot` = 'ויקרא את שם המקום ההוא קברות התאוה כי שם קברו את העם המתאוים' AND `text_maqafim` = 'ויקרא את-שם-המקום ההוא קברות התאוה כי-שם קברו את-העם המתאוים.' AND `text_niqud` = 'וַיִּקְרָא אֶת שֵׁם הַמָּקוֹם הַהוּא קִבְרוֹת הַתַּאֲוָה כִּי שָׁם קָבְרוּ אֶת הָעָם הַמִּתְאַוִּים' AND `text_niqud_pisuq` = 'וַיִּקְרָא אֶת שֵׁם הַמָּקוֹם הַהוּא קִבְרוֹת הַתַּאֲוָה כִּי שָׁם קָבְרוּ אֶת הָעָם הַמִּתְאַוִּים.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=34' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'מִקִּבְרוֹת הַתַּאֲוָה נָסְעוּ הָעָם חֲצֵרוֹת; וַיִּהְיוּ בַּחֲצֵרוֹת.' WHERE `id` = 'במדיא35' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יא' AND `verse_number` = 35 AND `verse_letter` = 'לה' AND `text_otiot` = 'מקברות התאוה נסעו העם חצרות ויהיו בחצרות' AND `text_maqafim` = 'מקברות התאוה נסעו העם חצרות ויהיו בחצרות.' AND `text_niqud` = 'מִקִּבְרוֹת הַתַּאֲוָה נָסְעוּ הָעָם חֲצֵרוֹת וַיִּהְיוּ בַּחֲצֵרוֹת' AND `text_niqud_pisuq` = 'מִקִּבְרוֹת הַתַּאֲוָה נָסְעוּ הָעָם חֲצֵרוֹת וַיִּהְיוּ בַּחֲצֵרוֹת.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0411.htm' AND `ktovt_sikum` = 'sfr=04&prq=11&psuq=35' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַתְּדַבֵּר מִרְיָם וְאַהֲרֹן בְּמֹשֶׁה, עַל-אֹדוֹת הָאִשָּׁה הַכֻּשִׁית אֲשֶׁר לָקָח; כִּי אִשָּׁה כֻשִׁית לָקָח.' WHERE `id` = 'במדיב1' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 1 AND `verse_letter` = 'א' AND `text_otiot` = 'ותדבר מרים ואהרן במשה על אדות האשה הכשית אשר לקח כי אשה כשית לקח' AND `text_maqafim` = 'ותדבר מרים ואהרן במשה על-אדות האשה הכשית אשר לקח כי-אשה כשית לקח.' AND `text_niqud` = 'וַתְּדַבֵּר מִרְיָם וְאַהֲרֹן בְּמֹשֶׁה עַל אֹדוֹת הָאִשָּׁה הַכֻּשִׁית אֲשֶׁר לָקָח כִּי אִשָּׁה כֻשִׁית לָקָח' AND `text_niqud_pisuq` = 'וַתְּדַבֵּר מִרְיָם וְאַהֲרֹן בְּמֹשֶׁה עַל אֹדוֹת הָאִשָּׁה הַכֻּשִׁית אֲשֶׁר לָקָח כִּי אִשָּׁה כֻשִׁית לָקָח.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=1' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמְרוּ \'הֲרַק אַךְ בְּמֹשֶׁה דִּבֶּר יְהוָה? הֲלֹא גַּם בָּנוּ דִבֵּר!\' וַיִּשְׁמַע יְהוָה.' WHERE `id` = 'במדיב2' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 2 AND `verse_letter` = 'ב' AND `text_otiot` = 'ויאמרו הרק אך במשה דבר יהוה הלא גם בנו דבר וישמע יהוה' AND `text_maqafim` = 'ויאמרו הרק אך-במשה דבר יהוה הלא גם-בנו דבר וישמע יהוה.' AND `text_niqud` = 'וַיֹּאמְרוּ הֲרַק אַךְ בְּמֹשֶׁה דִּבֶּר יְהוָה הֲלֹא גַּם בָּנוּ דִבֵּר וַיִּשְׁמַע יְהוָה' AND `text_niqud_pisuq` = 'וַיֹּאמְרוּ הֲרַק אַךְ בְּמֹשֶׁה דִּבֶּר יְהוָה הֲלֹא גַּם בָּנוּ דִבֵּר וַיִּשְׁמַע יְהוָה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=2' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהָאִישׁ מֹשֶׁה ענו[עָנָיו] מְאֹד; מִכֹּל הָאָדָם, אֲשֶׁר עַל פְּנֵי הָאֲדָמָה.' WHERE `id` = 'במדיב3' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 3 AND `verse_letter` = 'ג' AND `text_otiot` = 'והאיש משה ענו מאד מכל האדם אשר על פני האדמה' AND `text_maqafim` = 'והאיש משה ענו מאד מכל האדם אשר על-פני האדמה.' AND `text_niqud` = 'וְהָאִישׁ מֹשֶׁה <small>ענו</small> [עָנָיו] מְאֹד מִכֹּל הָאָדָם אֲשֶׁר עַל פְּנֵי הָאֲדָמָה' AND `text_niqud_pisuq` = 'וְהָאִישׁ מֹשֶׁה ענו[עָנָיו] מְאֹד מִכֹּל הָאָדָם אֲשֶׁר עַל פְּנֵי הָאֲדָמָה.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=3' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה פִּתְאֹם, אֶל מֹשֶׁה וְאֶל אַהֲרֹן וְאֶל מִרְיָם: \'צְאוּ שְׁלָשְׁתְּכֶם אֶל אֹהֶל מוֹעֵד!\' וַיֵּצְאוּ שְׁלָשְׁתָּם.' WHERE `id` = 'במדיב4' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 4 AND `verse_letter` = 'ד' AND `text_otiot` = 'ויאמר יהוה פתאם אל משה ואל אהרן ואל מרים צאו שלשתכם אל אהל מועד ויצאו שלשתם' AND `text_maqafim` = 'ויאמר יהוה פתאם אל-משה ואל-אהרן ואל-מרים צאו שלשתכם אל-אהל מועד ויצאו שלשתם.' AND `text_niqud` = 'וַיֹּאמֶר יְהוָה פִּתְאֹם אֶל מֹשֶׁה וְאֶל אַהֲרֹן וְאֶל מִרְיָם צְאוּ שְׁלָשְׁתְּכֶם אֶל אֹהֶל מוֹעֵד וַיֵּצְאוּ שְׁלָשְׁתָּם' AND `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה פִּתְאֹם אֶל מֹשֶׁה וְאֶל אַהֲרֹן וְאֶל מִרְיָם צְאוּ שְׁלָשְׁתְּכֶם אֶל אֹהֶל מוֹעֵד וַיֵּצְאוּ שְׁלָשְׁתָּם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=4' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֵּרֶד יְהוָה בְּעַמּוּד עָנָן, וַיַּעֲמֹד פֶּתַח הָאֹהֶל; וַיִּקְרָא \'אַהֲרֹן וּמִרְיָם!\' וַיֵּצְאוּ שְׁנֵיהֶם.' WHERE `id` = 'במדיב5' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 5 AND `verse_letter` = 'ה' AND `text_otiot` = 'וירד יהוה בעמוד ענן ויעמד פתח האהל ויקרא אהרן ומרים ויצאו שניהם' AND `text_maqafim` = 'וירד יהוה בעמוד ענן ויעמד פתח האהל ויקרא אהרן ומרים ויצאו שניהם.' AND `text_niqud` = 'וַיֵּרֶד יְהוָה בְּעַמּוּד עָנָן וַיַּעֲמֹד פֶּתַח הָאֹהֶל וַיִּקְרָא אַהֲרֹן וּמִרְיָם וַיֵּצְאוּ שְׁנֵיהֶם' AND `text_niqud_pisuq` = 'וַיֵּרֶד יְהוָה בְּעַמּוּד עָנָן וַיַּעֲמֹד פֶּתַח הָאֹהֶל וַיִּקְרָא אַהֲרֹן וּמִרְיָם וַיֵּצְאוּ שְׁנֵיהֶם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=5' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר \'שִׁמְעוּ נָא דְבָרָי: אִם יִהְיֶה נְבִיאֲכֶם, יְהוָה, בַּמַּרְאָה אֵלָיו אֶתְוַדָּע, בַּחֲלוֹם אֲדַבֶּר בּוֹ;\'' WHERE `id` = 'במדיב6' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 6 AND `verse_letter` = 'ו' AND `text_otiot` = 'ויאמר שמעו נא דברי אם יהיה נביאכם יהוה במראה אליו אתודע בחלום אדבר בו' AND `text_maqafim` = 'ויאמר שמעו-נא דברי אם-יהיה נביאכם יהוה במראה אליו אתודע בחלום אדבר-בו.' AND `text_niqud` = 'וַיֹּאמֶר שִׁמְעוּ נָא דְבָרָי אִם יִהְיֶה נְבִיאֲכֶם יְהוָה בַּמַּרְאָה אֵלָיו אֶתְוַדָּע בַּחֲלוֹם אֲדַבֶּר בּוֹ' AND `text_niqud_pisuq` = 'וַיֹּאמֶר שִׁמְעוּ נָא דְבָרָי אִם יִהְיֶה נְבִיאֲכֶם יְהוָה בַּמַּרְאָה אֵלָיו אֶתְוַדָּע בַּחֲלוֹם אֲדַבֶּר בּוֹ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=6' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'- לֹא כֵן עַבְדִּי מֹשֶׁה,  בְּכָל בֵּיתִי נֶאֱמָן הוּא;\'' WHERE `id` = 'במדיב7' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 7 AND `verse_letter` = 'ז' AND `text_otiot` = 'לא כן עבדי משה בכל ביתי נאמן הוא' AND `text_maqafim` = 'לא-כן עבדי משה בכל-ביתי נאמן הוא.' AND `text_niqud` = 'לֹא כֵן עַבְדִּי מֹשֶׁה בְּכָל בֵּיתִי נֶאֱמָן הוּא' AND `text_niqud_pisuq` = 'לֹא כֵן עַבְדִּי מֹשֶׁה בְּכָל בֵּיתִי נֶאֱמָן הוּא.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=7' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'- פֶּה אֶל פֶּה אֲדַבֶּר בּוֹ, וּמַרְאֶה וְלֹא בְחִידֹת, וּתְמֻנַת יְהוָה יַבִּיט; וּמַדּוּעַ לֹא יְרֵאתֶם, לְדַבֵּר בְּעַבְדִּי בְמֹשֶׁה?\'' WHERE `id` = 'במדיב8' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 8 AND `verse_letter` = 'ח' AND `text_otiot` = 'פה אל פה אדבר בו ומראה ולא בחידת ותמנת יהוה יביט ומדוע לא יראתם לדבר בעבדי במשה' AND `text_maqafim` = 'פה אל-פה אדבר-בו ומראה ולא בחידת ותמנת יהוה יביט ומדוע לא יראתם לדבר בעבדי במשה.' AND `text_niqud` = 'פֶּה אֶל פֶּה אֲדַבֶּר בּוֹ וּמַרְאֶה וְלֹא בְחִידֹת וּתְמֻנַת יְהוָה יַבִּיט וּמַדּוּעַ לֹא יְרֵאתֶם לְדַבֵּר בְּעַבְדִּי בְמֹשֶׁה' AND `text_niqud_pisuq` = 'פֶּה אֶל פֶּה אֲדַבֶּר בּוֹ וּמַרְאֶה וְלֹא בְחִידֹת וּתְמֻנַת יְהוָה יַבִּיט וּמַדּוּעַ לֹא יְרֵאתֶם לְדַבֵּר בְּעַבְדִּי בְמֹשֶׁה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=8' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּחַר אַף יְהוָה בָּם, וַיֵּלַךְ.' WHERE `id` = 'במדיב9' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 9 AND `verse_letter` = 'ט' AND `text_otiot` = 'ויחר אף יהוה בם וילך' AND `text_maqafim` = 'ויחר אף יהוה בם וילך.' AND `text_niqud` = 'וַיִּחַר אַף יְהוָה בָּם וַיֵּלַךְ' AND `text_niqud_pisuq` = 'וַיִּחַר אַף יְהוָה בָּם וַיֵּלַךְ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=9' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְהֶעָנָן סָר מֵעַל הָאֹהֶל, וְהִנֵּה מִרְיָם מְצֹרַעַת כַּשָּׁלֶג; וַיִּפֶן אַהֲרֹן אֶל מִרְיָם, וְהִנֵּה מְצֹרָעַת.' WHERE `id` = 'במדיב10' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 10 AND `verse_letter` = 'י' AND `text_otiot` = 'והענן סר מעל האהל והנה מרים מצרעת כשלג ויפן אהרן אל מרים והנה מצרעת' AND `text_maqafim` = 'והענן סר מעל האהל והנה מרים מצרעת כשלג ויפן אהרן אל-מרים והנה מצרעת.' AND `text_niqud` = 'וְהֶעָנָן סָר מֵעַל הָאֹהֶל וְהִנֵּה מִרְיָם מְצֹרַעַת כַּשָּׁלֶג וַיִּפֶן אַהֲרֹן אֶל מִרְיָם וְהִנֵּה מְצֹרָעַת' AND `text_niqud_pisuq` = 'וְהֶעָנָן סָר מֵעַל הָאֹהֶל וְהִנֵּה מִרְיָם מְצֹרַעַת כַּשָּׁלֶג וַיִּפֶן אַהֲרֹן אֶל מִרְיָם וְהִנֵּה מְצֹרָעַת.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=10' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר אַהֲרֹן אֶל מֹשֶׁה \'בִּי אֲדֹנִי! אַל נָא תָשֵׁת עָלֵינוּ חַטָּאת, אֲשֶׁר נוֹאַלְנוּ וַאֲשֶׁר חָטָאנוּ!\'' WHERE `id` = 'במדיב11' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 11 AND `verse_letter` = 'יא' AND `text_otiot` = 'ויאמר אהרן אל משה בי אדני אל נא תשת עלינו חטאת אשר נואלנו ואשר חטאנו' AND `text_maqafim` = 'ויאמר אהרן אל-משה בי אדני אל-נא תשת עלינו חטאת אשר נואלנו ואשר חטאנו.' AND `text_niqud` = 'וַיֹּאמֶר אַהֲרֹן אֶל מֹשֶׁה בִּי אֲדֹנִי אַל נָא תָשֵׁת עָלֵינוּ חַטָּאת אֲשֶׁר נוֹאַלְנוּ וַאֲשֶׁר חָטָאנוּ' AND `text_niqud_pisuq` = 'וַיֹּאמֶר אַהֲרֹן אֶל מֹשֶׁה בִּי אֲדֹנִי אַל נָא תָשֵׁת עָלֵינוּ חַטָּאת אֲשֶׁר נוֹאַלְנוּ וַאֲשֶׁר חָטָאנוּ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=11' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'אַל נָא תְהִי כַּמֵּת; אֲשֶׁר בְּצֵאתוֹ מֵרֶחֶם אִמּוֹ, וַיֵּאָכֵל חֲצִי בְשָׂרוֹ!\'' WHERE `id` = 'במדיב12' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 12 AND `verse_letter` = 'יב' AND `text_otiot` = 'אל נא תהי כמת אשר בצאתו מרחם אמו ויאכל חצי בשרו' AND `text_maqafim` = 'אל-נא תהי כמת אשר בצאתו מרחם אמו ויאכל חצי בשרו.' AND `text_niqud` = 'אַל נָא תְהִי כַּמֵּת אֲשֶׁר בְּצֵאתוֹ מֵרֶחֶם אִמּוֹ וַיֵּאָכֵל חֲצִי בְשָׂרוֹ' AND `text_niqud_pisuq` = 'אַל נָא תְהִי כַּמֵּת אֲשֶׁר בְּצֵאתוֹ מֵרֶחֶם אִמּוֹ וַיֵּאָכֵל חֲצִי בְשָׂרוֹ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=12' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּצְעַק מֹשֶׁה אֶל יְהוָה לֵאמֹר \'אֵל נָא רְפָא נָא לָהּ!\'' WHERE `id` = 'במדיב13' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 13 AND `verse_letter` = 'יג' AND `text_otiot` = 'ויצעק משה אל יהוה לאמר אל נא רפא נא לה' AND `text_maqafim` = 'ויצעק משה אל-יהוה לאמר אל נא רפא נא לה.' AND `text_niqud` = 'וַיִּצְעַק מֹשֶׁה אֶל יְהוָה לֵאמֹר אֵל נָא רְפָא נָא לָהּ' AND `text_niqud_pisuq` = 'וַיִּצְעַק מֹשֶׁה אֶל יְהוָה לֵאמֹר אֵל נָא רְפָא נָא לָהּ.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=13' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה \'וְאָבִיהָ יָרֹק יָרַק בְּפָנֶיהָ, הֲלֹא תִכָּלֵם שִׁבְעַת יָמִים? תִּסָּגֵר שִׁבְעַת יָמִים מִחוּץ לַמַּחֲנֶה, וְאַחַר תֵּאָסֵף.\'' WHERE `id` = 'במדיב14' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 14 AND `verse_letter` = 'יד' AND `text_otiot` = 'ויאמר יהוה אל משה ואביה ירק ירק בפניה הלא תכלם שבעת ימים תסגר שבעת ימים מחוץ למחנה ואחר תאסף' AND `text_maqafim` = 'ויאמר יהוה אל-משה ואביה ירק ירק בפניה הלא תכלם שבעת ימים תסגר שבעת ימים מחוץ למחנה ואחר תאסף.' AND `text_niqud` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה וְאָבִיהָ יָרֹק יָרַק בְּפָנֶיהָ הֲלֹא תִכָּלֵם שִׁבְעַת יָמִים תִּסָּגֵר שִׁבְעַת יָמִים מִחוּץ לַמַּחֲנֶה וְאַחַר תֵּאָסֵף' AND `text_niqud_pisuq` = 'וַיֹּאמֶר יְהוָה אֶל מֹשֶׁה וְאָבִיהָ יָרֹק יָרַק בְּפָנֶיהָ הֲלֹא תִכָּלֵם שִׁבְעַת יָמִים תִּסָּגֵר שִׁבְעַת יָמִים מִחוּץ לַמַּחֲנֶה וְאַחַר תֵּאָסֵף.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=14' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַתִּסָּגֵר מִרְיָם מִחוּץ לַמַּחֲנֶה שִׁבְעַת יָמִים; וְהָעָם לֹא נָסַע, עַד הֵאָסֵף מִרְיָם.' WHERE `id` = 'במדיב15' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 15 AND `verse_letter` = 'טו' AND `text_otiot` = 'ותסגר מרים מחוץ למחנה שבעת ימים והעם לא נסע עד האסף מרים' AND `text_maqafim` = 'ותסגר מרים מחוץ למחנה שבעת ימים והעם לא נסע עד-האסף מרים.' AND `text_niqud` = 'וַתִּסָּגֵר מִרְיָם מִחוּץ לַמַּחֲנֶה שִׁבְעַת יָמִים וְהָעָם לֹא נָסַע עַד הֵאָסֵף מִרְיָם' AND `text_niqud_pisuq` = 'וַתִּסָּגֵר מִרְיָם מִחוּץ לַמַּחֲנֶה שִׁבְעַת יָמִים וְהָעָם לֹא נָסַע עַד הֵאָסֵף מִרְיָם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=15' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְאַחַר נָסְעוּ הָעָם מֵחֲצֵרוֹת; וַיַּחֲנוּ בְּמִדְבַּר פָּארָן.' WHERE `id` = 'במדיב16' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יב' AND `verse_number` = 16 AND `verse_letter` = 'טז' AND `text_otiot` = 'ואחר נסעו העם מחצרות ויחנו במדבר פארן' AND `text_maqafim` = 'ואחר נסעו העם מחצרות ויחנו במדבר פארן.' AND `text_niqud` = 'וְאַחַר נָסְעוּ הָעָם מֵחֲצֵרוֹת וַיַּחֲנוּ בְּמִדְבַּר פָּארָן' AND `text_niqud_pisuq` = 'וְאַחַר נָסְעוּ הָעָם מֵחֲצֵרוֹת וַיַּחֲנוּ בְּמִדְבַּר פָּארָן.' AND `text_teamim` = '' AND `after_text` = '/P' AND `ktovt_prq` = 'prqim/t0412.htm' AND `ktovt_sikum` = 'sfr=04&prq=12&psuq=16' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיְדַבֵּר יְהוָה אֶל מֹשֶׁה לֵּאמֹר:' WHERE `id` = 'במדיג1' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 1 AND `verse_letter` = 'א' AND `text_otiot` = 'וידבר יהוה אל משה לאמר' AND `text_maqafim` = 'וידבר יהוה אל-משה לאמר.' AND `text_niqud` = 'וַיְדַבֵּר יְהוָה אֶל מֹשֶׁה לֵּאמֹר' AND `text_niqud_pisuq` = 'וַיְדַבֵּר יְהוָה אֶל מֹשֶׁה לֵּאמֹר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=1' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'שְׁלַח לְךָ אֲנָשִׁים, וְיָתֻרוּ אֶת אֶרֶץ כְּנַעַן, אֲשֶׁר אֲנִי נֹתֵן לִבְנֵי-יִשְׂרָאֵל; אִישׁ אֶחָד אִישׁ אֶחָד לְמַטֵּה אֲבֹתָיו תִּשְׁלָחוּ, כֹּל נָשִׂיא בָהֶם.' WHERE `id` = 'במדיג2' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 2 AND `verse_letter` = 'ב' AND `text_otiot` = 'שלח לך אנשים ויתרו את ארץ כנען אשר אני נתן לבני ישראל איש אחד איש אחד למטה אבתיו תשלחו כל נשיא בהם' AND `text_maqafim` = 'שלח-לך אנשים ויתרו את-ארץ כנען אשר-אני נתן לבני ישראל איש אחד איש אחד למטה אבתיו תשלחו כל נשיא בהם.' AND `text_niqud` = 'שְׁלַח לְךָ אֲנָשִׁים וְיָתֻרוּ אֶת אֶרֶץ כְּנַעַן אֲשֶׁר אֲנִי נֹתֵן לִבְנֵי יִשְׂרָאֵל אִישׁ אֶחָד אִישׁ אֶחָד לְמַטֵּה אֲבֹתָיו תִּשְׁלָחוּ כֹּל נָשִׂיא בָהֶם' AND `text_niqud_pisuq` = 'שְׁלַח לְךָ אֲנָשִׁים וְיָתֻרוּ אֶת אֶרֶץ כְּנַעַן אֲשֶׁר אֲנִי נֹתֵן לִבְנֵי-יִשְׂרָאֵל אִישׁ אֶחָד אִישׁ אֶחָד לְמַטֵּה אֲבֹתָיו תִּשְׁלָחוּ כֹּל נָשִׂיא בָהֶם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=2' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּשְׁלַח אֹתָם מֹשֶׁה מִמִּדְבַּר פָּארָן, עַל-פִּי יְהוָה; כֻּלָּם אֲנָשִׁים, רָאשֵׁי בְנֵי-יִשְׂרָאֵל הֵמָּה..' WHERE `id` = 'במדיג3' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 3 AND `verse_letter` = 'ג' AND `text_otiot` = 'וישלח אתם משה ממדבר פארן על פי יהוה כלם אנשים ראשי בני ישראל המה' AND `text_maqafim` = 'וישלח אתם משה ממדבר פארן על-פי יהוה כלם אנשים ראשי בני-ישראל המה.' AND `text_niqud` = 'וַיִּשְׁלַח אֹתָם מֹשֶׁה מִמִּדְבַּר פָּארָן עַל פִּי יְהוָה כֻּלָּם אֲנָשִׁים רָאשֵׁי בְנֵי יִשְׂרָאֵל הֵמָּה' AND `text_niqud_pisuq` = 'וַיִּשְׁלַח אֹתָם מֹשֶׁה מִמִּדְבַּר פָּארָן עַל-פִּי יְהוָה כֻּלָּם אֲנָשִׁים רָאשֵׁי בְנֵי-יִשְׂרָאֵל הֵמָּה..' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=3' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וְאֵלֶּה שְׁמוֹתָם: לְמַטֵּה רְאוּבֵן, שַׁמּוּעַ בֶּן זַכּוּר.' WHERE `id` = 'במדיג4' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 4 AND `verse_letter` = 'ד' AND `text_otiot` = 'ואלה שמותם למטה ראובן שמוע בן זכור' AND `text_maqafim` = 'ואלה שמותם למטה ראובן שמוע בן-זכור.' AND `text_niqud` = 'וְאֵלֶּה שְׁמוֹתָם לְמַטֵּה רְאוּבֵן שַׁמּוּעַ בֶּן זַכּוּר' AND `text_niqud_pisuq` = 'וְאֵלֶּה שְׁמוֹתָם לְמַטֵּה רְאוּבֵן שַׁמּוּעַ בֶּן זַכּוּר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=4' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה שִׁמְעוֹן, שָׁפָט בֶּן חוֹרִי.' WHERE `id` = 'במדיג5' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 5 AND `verse_letter` = 'ה' AND `text_otiot` = 'למטה שמעון שפט בן חורי' AND `text_maqafim` = 'למטה שמעון שפט בן-חורי.' AND `text_niqud` = 'לְמַטֵּה שִׁמְעוֹן שָׁפָט בֶּן חוֹרִי' AND `text_niqud_pisuq` = 'לְמַטֵּה שִׁמְעוֹן שָׁפָט בֶּן חוֹרִי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=5' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה יְהוּדָה, כָּלֵב בֶּן-יְפֻנֶּה.' WHERE `id` = 'במדיג6' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 6 AND `verse_letter` = 'ו' AND `text_otiot` = 'למטה יהודה כלב בן יפנה' AND `text_maqafim` = 'למטה יהודה כלב בן-יפנה.' AND `text_niqud` = 'לְמַטֵּה יְהוּדָה כָּלֵב בֶּן יְפֻנֶּה' AND `text_niqud_pisuq` = 'לְמַטֵּה יְהוּדָה כָּלֵב בֶּן-יְפֻנֶּה.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=6' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה יִשָּׂשכָר, יִגְאָל בֶּן יוֹסֵף.' WHERE `id` = 'במדיג7' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 7 AND `verse_letter` = 'ז' AND `text_otiot` = 'למטה יששכר יגאל בן יוסף' AND `text_maqafim` = 'למטה יששכר יגאל בן-יוסף.' AND `text_niqud` = 'לְמַטֵּה יִשָּׂשכָר יִגְאָל בֶּן יוֹסֵף' AND `text_niqud_pisuq` = 'לְמַטֵּה יִשָּׂשכָר יִגְאָל בֶּן יוֹסֵף.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=7' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה אֶפְרָיִם, הוֹשֵׁעַ בִּן-נוּן.' WHERE `id` = 'במדיג8' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 8 AND `verse_letter` = 'ח' AND `text_otiot` = 'למטה אפרים הושע בן נון' AND `text_maqafim` = 'למטה אפרים הושע בן-נון.' AND `text_niqud` = 'לְמַטֵּה אֶפְרָיִם הוֹשֵׁעַ בִּן נוּן' AND `text_niqud_pisuq` = 'לְמַטֵּה אֶפְרָיִם הוֹשֵׁעַ בִּן-נוּן.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=8' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה בִנְיָמִן, פַּלְטִי בֶּן רָפוּא.' WHERE `id` = 'במדיג9' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 9 AND `verse_letter` = 'ט' AND `text_otiot` = 'למטה בנימן פלטי בן רפוא' AND `text_maqafim` = 'למטה בנימן פלטי בן-רפוא.' AND `text_niqud` = 'לְמַטֵּה בִנְיָמִן פַּלְטִי בֶּן רָפוּא' AND `text_niqud_pisuq` = 'לְמַטֵּה בִנְיָמִן פַּלְטִי בֶּן רָפוּא.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=9' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה זְבוּלֻן, גַּדִּיאֵל בֶּן סוֹדִי.' WHERE `id` = 'במדיג10' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 10 AND `verse_letter` = 'י' AND `text_otiot` = 'למטה זבולן גדיאל בן סודי' AND `text_maqafim` = 'למטה זבולן גדיאל בן-סודי.' AND `text_niqud` = 'לְמַטֵּה זְבוּלֻן גַּדִּיאֵל בֶּן סוֹדִי' AND `text_niqud_pisuq` = 'לְמַטֵּה זְבוּלֻן גַּדִּיאֵל בֶּן סוֹדִי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=10' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה יוֹסֵף; לְמַטֵּה מְנַשֶּׁה, גַּדִּי בֶּן סוּסִי. *' WHERE `id` = 'במדיג11' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 11 AND `verse_letter` = 'יא' AND `text_otiot` = 'למטה יוסף למטה מנשה גדי בן סוסי' AND `text_maqafim` = 'למטה יוסף למטה מנשה גדי בן-סוסי.' AND `text_niqud` = 'לְמַטֵּה יוֹסֵף לְמַטֵּה מְנַשֶּׁה גַּדִּי בֶּן סוּסִי' AND `text_niqud_pisuq` = 'לְמַטֵּה יוֹסֵף לְמַטֵּה מְנַשֶּׁה גַּדִּי בֶּן סוּסִי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=11' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה דָן, עַמִּיאֵל בֶּן גְּמַלִּי.' WHERE `id` = 'במדיג12' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 12 AND `verse_letter` = 'יב' AND `text_otiot` = 'למטה דן עמיאל בן גמלי' AND `text_maqafim` = 'למטה דן עמיאל בן-גמלי.' AND `text_niqud` = 'לְמַטֵּה דָן עַמִּיאֵל בֶּן גְּמַלִּי' AND `text_niqud_pisuq` = 'לְמַטֵּה דָן עַמִּיאֵל בֶּן גְּמַלִּי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=12' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה אָשֵׁר, סְתוּר בֶּן מִיכָאֵל.' WHERE `id` = 'במדיג13' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 13 AND `verse_letter` = 'יג' AND `text_otiot` = 'למטה אשר סתור בן מיכאל' AND `text_maqafim` = 'למטה אשר סתור בן-מיכאל.' AND `text_niqud` = 'לְמַטֵּה אָשֵׁר סְתוּר בֶּן מִיכָאֵל' AND `text_niqud_pisuq` = 'לְמַטֵּה אָשֵׁר סְתוּר בֶּן מִיכָאֵל.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=13' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה נַפְתָּלִי, נַחְבִּי בֶּן וָפְסִי.' WHERE `id` = 'במדיג14' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 14 AND `verse_letter` = 'יד' AND `text_otiot` = 'למטה נפתלי נחבי בן ופסי' AND `text_maqafim` = 'למטה נפתלי נחבי בן-ופסי.' AND `text_niqud` = 'לְמַטֵּה נַפְתָּלִי נַחְבִּי בֶּן וָפְסִי' AND `text_niqud_pisuq` = 'לְמַטֵּה נַפְתָּלִי נַחְבִּי בֶּן וָפְסִי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=14' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לְמַטֵּה גָד, גְּאוּאֵל בֶּן מָכִי.' WHERE `id` = 'במדיג15' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 15 AND `verse_letter` = 'טו' AND `text_otiot` = 'למטה גד גאואל בן מכי' AND `text_maqafim` = 'למטה גד גאואל בן-מכי.' AND `text_niqud` = 'לְמַטֵּה גָד גְּאוּאֵל בֶּן מָכִי' AND `text_niqud_pisuq` = 'לְמַטֵּה גָד גְּאוּאֵל בֶּן מָכִי.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=15' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'אֵלֶּה שְׁמוֹת הָאֲנָשִׁים, אֲשֶׁר שָׁלַח מֹשֶׁה לָתוּר אֶת הָאָרֶץ; וַיִּקְרָא מֹשֶׁה לְהוֹשֵׁעַ בִּן-נוּן \"יְהוֹשֻׁעַ\".' WHERE `id` = 'במדיג16' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 16 AND `verse_letter` = 'טז' AND `text_otiot` = 'אלה שמות האנשים אשר שלח משה לתור את הארץ ויקרא משה להושע בן נון יהושע' AND `text_maqafim` = 'אלה שמות האנשים אשר-שלח משה לתור את-הארץ ויקרא משה להושע בן-נון יהושע.' AND `text_niqud` = 'אֵלֶּה שְׁמוֹת הָאֲנָשִׁים אֲשֶׁר שָׁלַח מֹשֶׁה לָתוּר אֶת הָאָרֶץ וַיִּקְרָא מֹשֶׁה לְהוֹשֵׁעַ בִּן נוּן יְהוֹשֻׁעַ' AND `text_niqud_pisuq` = 'אֵלֶּה שְׁמוֹת הָאֲנָשִׁים אֲשֶׁר שָׁלַח מֹשֶׁה לָתוּר אֶת הָאָרֶץ וַיִּקְרָא מֹשֶׁה לְהוֹשֵׁעַ בִּן-נוּן יְהוֹשֻׁעַ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=16' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיִּשְׁלַח אֹתָם מֹשֶׁה, לָתוּר אֶת אֶרֶץ כְּנָעַן; וַיֹּאמֶר אֲלֵהֶם \'עֲלוּ זֶה בַּנֶּגֶב, וַעֲלִיתֶם אֶת הָהָר.\'' WHERE `id` = 'במדיג17' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 17 AND `verse_letter` = 'יז' AND `text_otiot` = 'וישלח אתם משה לתור את ארץ כנען ויאמר אלהם עלו זה בנגב ועליתם את ההר' AND `text_maqafim` = 'וישלח אתם משה לתור את-ארץ כנען ויאמר אלהם עלו זה בנגב ועליתם את-ההר.' AND `text_niqud` = 'וַיִּשְׁלַח אֹתָם מֹשֶׁה לָתוּר אֶת אֶרֶץ כְּנָעַן וַיֹּאמֶר אֲלֵהֶם עֲלוּ זֶה בַּנֶּגֶב וַעֲלִיתֶם אֶת הָהָר' AND `text_niqud_pisuq` = 'וַיִּשְׁלַח אֹתָם מֹשֶׁה לָתוּר אֶת אֶרֶץ כְּנָעַן וַיֹּאמֶר אֲלֵהֶם עֲלוּ זֶה בַּנֶּגֶב וַעֲלִיתֶם אֶת הָהָר.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=17' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וּרְאִיתֶם אֶת הָאָרֶץ, מַה הִוא? וְאֶת הָעָם הַיֹּשֵׁב עָלֶיהָ, הֶחָזָק הוּא הֲרָפֶה? הַמְעַט הוּא אִם רָב?\'' WHERE `id` = 'במדיג18' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 18 AND `verse_letter` = 'יח' AND `text_otiot` = 'וראיתם את הארץ מה הוא ואת העם הישב עליה החזק הוא הרפה המעט הוא אם רב' AND `text_maqafim` = 'וראיתם את-הארץ מה-הוא ואת-העם הישב עליה החזק הוא הרפה המעט הוא אם-רב.' AND `text_niqud` = 'וּרְאִיתֶם אֶת הָאָרֶץ מַה הִוא וְאֶת הָעָם הַיֹּשֵׁב עָלֶיהָ הֶחָזָק הוּא הֲרָפֶה הַמְעַט הוּא אִם רָב' AND `text_niqud_pisuq` = 'וּרְאִיתֶם אֶת הָאָרֶץ מַה הִוא וְאֶת הָעָם הַיֹּשֵׁב עָלֶיהָ הֶחָזָק הוּא הֲרָפֶה הַמְעַט הוּא אִם רָב.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=18' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וּמָה הָאָרֶץ אֲשֶׁר הוּא יֹשֵׁב בָּהּ, הֲטוֹבָה הִוא אִם רָעָה? וּמָה הֶעָרִים אֲשֶׁר הוּא יוֹשֵׁב בָּהֵנָּה, הַבְּמַחֲנִים אִם בְּמִבְצָרִים?\'' WHERE `id` = 'במדיג19' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 19 AND `verse_letter` = 'יט' AND `text_otiot` = 'ומה הארץ אשר הוא ישב בה הטובה הוא אם רעה ומה הערים אשר הוא יושב בהנה הבמחנים אם במבצרים' AND `text_maqafim` = 'ומה הארץ אשר-הוא ישב בה הטובה הוא אם-רעה ומה הערים אשר-הוא יושב בהנה הבמחנים אם במבצרים.' AND `text_niqud` = 'וּמָה הָאָרֶץ אֲשֶׁר הוּא יֹשֵׁב בָּהּ הֲטוֹבָה הִוא אִם רָעָה וּמָה הֶעָרִים אֲשֶׁר הוּא יוֹשֵׁב בָּהֵנָּה הַבְּמַחֲנִים אִם בְּמִבְצָרִים' AND `text_niqud_pisuq` = 'וּמָה הָאָרֶץ אֲשֶׁר הוּא יֹשֵׁב בָּהּ הֲטוֹבָה הִוא אִם רָעָה וּמָה הֶעָרִים אֲשֶׁר הוּא יוֹשֵׁב בָּהֵנָּה הַבְּמַחֲנִים אִם בְּמִבְצָרִים.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=19' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = '\'וּמָה הָאָרֶץ, הַשְּׁמֵנָה הִוא אִם רָזָה, הֲיֵשׁ בָּהּ עֵץ אִם אַיִן? וְהִתְחַזַּקְתֶּם, וּלְקַחְתֶּם מִפְּרִי הָאָרֶץ; וְהַיָּמִים, יְמֵי בִּכּוּרֵי עֲנָבִים.\'' WHERE `id` = 'במדיג20' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 20 AND `verse_letter` = 'כ' AND `text_otiot` = 'ומה הארץ השמנה הוא אם רזה היש בה עץ אם אין והתחזקתם ולקחתם מפרי הארץ והימים ימי בכורי ענבים' AND `text_maqafim` = 'ומה הארץ השמנה הוא אם-רזה היש-בה עץ אם-אין והתחזקתם ולקחתם מפרי הארץ והימים ימי בכורי ענבים.' AND `text_niqud` = 'וּמָה הָאָרֶץ הַשְּׁמֵנָה הִוא אִם רָזָה הֲיֵשׁ בָּהּ עֵץ אִם אַיִן וְהִתְחַזַּקְתֶּם וּלְקַחְתֶּם מִפְּרִי הָאָרֶץ וְהַיָּמִים יְמֵי בִּכּוּרֵי עֲנָבִים' AND `text_niqud_pisuq` = 'וּמָה הָאָרֶץ הַשְּׁמֵנָה הִוא אִם רָזָה הֲיֵשׁ בָּהּ עֵץ אִם אַיִן וְהִתְחַזַּקְתֶּם וּלְקַחְתֶּם מִפְּרִי הָאָרֶץ וְהַיָּמִים יְמֵי בִּכּוּרֵי עֲנָבִים.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=20' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיַּעֲלוּ, וַיָּתֻרוּ אֶת הָאָרֶץ; מִמִּדְבַּר צִן עַד רְחֹב, לְבֹא חֲמָת.' WHERE `id` = 'במדיג21' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 21 AND `verse_letter` = 'כא' AND `text_otiot` = 'ויעלו ויתרו את הארץ ממדבר צן עד רחב לבא חמת' AND `text_maqafim` = 'ויעלו ויתרו את-הארץ ממדבר-צן עד-רחב לבא חמת.' AND `text_niqud` = 'וַיַּעֲלוּ וַיָּתֻרוּ אֶת הָאָרֶץ מִמִּדְבַּר צִן עַד רְחֹב לְבֹא חֲמָת' AND `text_niqud_pisuq` = 'וַיַּעֲלוּ וַיָּתֻרוּ אֶת הָאָרֶץ מִמִּדְבַּר צִן עַד רְחֹב לְבֹא חֲמָת.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=21' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיַּעֲלוּ בַנֶּגֶב, וַיָּבֹא עַד חֶבְרוֹן; וְשָׁם אֲחִימַן שֵׁשַׁי וְתַלְמַי, יְלִידֵי הָעֲנָק; וְחֶבְרוֹן, שֶׁבַע שָׁנִים נִבְנְתָה, לִפְנֵי צֹעַן מִצְרָיִם.' WHERE `id` = 'במדיג22' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 22 AND `verse_letter` = 'כב' AND `text_otiot` = 'ויעלו בנגב ויבא עד חברון ושם אחימן ששי ותלמי ילידי הענק וחברון שבע שנים נבנתה לפני צען מצרים' AND `text_maqafim` = 'ויעלו בנגב ויבא עד-חברון ושם אחימן ששי ותלמי ילידי הענק וחברון שבע שנים נבנתה לפני צען מצרים.' AND `text_niqud` = 'וַיַּעֲלוּ בַנֶּגֶב וַיָּבֹא עַד חֶבְרוֹן וְשָׁם אֲחִימַן שֵׁשַׁי וְתַלְמַי יְלִידֵי הָעֲנָק וְחֶבְרוֹן שֶׁבַע שָׁנִים נִבְנְתָה לִפְנֵי צֹעַן מִצְרָיִם' AND `text_niqud_pisuq` = 'וַיַּעֲלוּ בַנֶּגֶב וַיָּבֹא עַד חֶבְרוֹן וְשָׁם אֲחִימַן שֵׁשַׁי וְתַלְמַי יְלִידֵי הָעֲנָק וְחֶבְרוֹן שֶׁבַע שָׁנִים נִבְנְתָה לִפְנֵי צֹעַן מִצְרָיִם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=22' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיָּבֹאוּ עַד נַחַל אֶשְׁכֹּל, וַיִּכְרְתוּ מִשָּׁם זְמוֹרָה וְאֶשְׁכּוֹל עֲנָבִים אֶחָד, וַיִּשָּׂאֻהוּ בַמּוֹט בִּשְׁנָיִם; וּמִן הָרִמֹּנִים, וּמִן הַתְּאֵנִים.' WHERE `id` = 'במדיג23' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 23 AND `verse_letter` = 'כג' AND `text_otiot` = 'ויבאו עד נחל אשכל ויכרתו משם זמורה ואשכול ענבים אחד וישאהו במוט בשנים ומן הרמנים ומן התאנים' AND `text_maqafim` = 'ויבאו עד-נחל אשכל ויכרתו משם זמורה ואשכול ענבים אחד וישאהו במוט בשנים ומן-הרמנים ומן-התאנים.' AND `text_niqud` = 'וַיָּבֹאוּ עַד נַחַל אֶשְׁכֹּל וַיִּכְרְתוּ מִשָּׁם זְמוֹרָה וְאֶשְׁכּוֹל עֲנָבִים אֶחָד וַיִּשָּׂאֻהוּ בַמּוֹט בִּשְׁנָיִם וּמִן הָרִמֹּנִים וּמִן הַתְּאֵנִים' AND `text_niqud_pisuq` = 'וַיָּבֹאוּ עַד נַחַל אֶשְׁכֹּל וַיִּכְרְתוּ מִשָּׁם זְמוֹרָה וְאֶשְׁכּוֹל עֲנָבִים אֶחָד וַיִּשָּׂאֻהוּ בַמּוֹט בִּשְׁנָיִם וּמִן הָרִמֹּנִים וּמִן הַתְּאֵנִים.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=23' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'לַמָּקוֹם הַהוּא קָרָא \"נַחַל אֶשְׁכּוֹל\"; עַל אֹדוֹת הָאֶשְׁכּוֹל, אֲשֶׁר כָּרְתוּ מִשָּׁם בְּנֵי-יִשְׂרָאֵל.' WHERE `id` = 'במדיג24' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 24 AND `verse_letter` = 'כד' AND `text_otiot` = 'למקום ההוא קרא נחל אשכול על אדות האשכול אשר כרתו משם בני ישראל' AND `text_maqafim` = 'למקום ההוא קרא נחל אשכול על אדות האשכול אשר-כרתו משם בני ישראל.' AND `text_niqud` = 'לַמָּקוֹם הַהוּא קָרָא נַחַל אֶשְׁכּוֹל עַל אֹדוֹת הָאֶשְׁכּוֹל אֲשֶׁר כָּרְתוּ מִשָּׁם בְּנֵי יִשְׂרָאֵל' AND `text_niqud_pisuq` = 'לַמָּקוֹם הַהוּא קָרָא נַחַל אֶשְׁכּוֹל עַל אֹדוֹת הָאֶשְׁכּוֹל אֲשֶׁר כָּרְתוּ מִשָּׁם בְּנֵי-יִשְׂרָאֵל.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=24' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיָּשֻׁבוּ מִתּוּר הָאָרֶץ; מִקֵּץ אַרְבָּעִים יוֹם.' WHERE `id` = 'במדיג25' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 25 AND `verse_letter` = 'כה' AND `text_otiot` = 'וישבו מתור הארץ מקץ ארבעים יום' AND `text_maqafim` = 'וישבו מתור הארץ מקץ ארבעים יום.' AND `text_niqud` = 'וַיָּשֻׁבוּ מִתּוּר הָאָרֶץ מִקֵּץ אַרְבָּעִים יוֹם' AND `text_niqud_pisuq` = 'וַיָּשֻׁבוּ מִתּוּר הָאָרֶץ מִקֵּץ אַרְבָּעִים יוֹם.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=25' AND 1 LIMIT 1;

SET character_set_client=utf8;
SET character_set_connection=utf8;
UPDATE `psuqim` SET `text_niqud_pisuq` = 'וַיֵּלְכוּ וַיָּבֹאוּ אֶל מֹשֶׁה וְאֶל אַהֲרֹן וְאֶל כָּל עֲדַת בְּנֵי-יִשְׂרָאֵל אֶל מִדְבַּר פָּארָן, קָדֵשָׁה; וַיָּשִׁיבוּ אוֹתָם דָּבָר וְאֶת כָּל הָעֵדָה, וַיַּרְאוּם אֶת פְּרִי הָאָרֶץ.' WHERE `id` = 'במדיג26' AND `book_code` = 'במד' AND `book_name` = 'במדבר' AND `chapter_letter` = 'יג' AND `verse_number` = 26 AND `verse_letter` = 'כו' AND `text_otiot` = 'וילכו ויבאו אל משה ואל אהרן ואל כל עדת בני ישראל אל מדבר פארן קדשה וישיבו אתם דבר ואת כל העדה ויראום את פרי הארץ' AND `text_maqafim` = 'וילכו ויבאו אל-משה ואל-אהרן ואל-כל-עדת בני-ישראל אל-מדבר פארן קדשה וישיבו אתם דבר ואת-כל-העדה ויראום את-פרי הארץ.' AND `text_niqud` = 'וַיֵּלְכוּ וַיָּבֹאוּ אֶל מֹשֶׁה וְאֶל אַהֲרֹן וְאֶל כָּל עֲדַת בְּנֵי יִשְׂרָאֵל אֶל מִדְבַּר פָּארָן קָדֵשָׁה וַיָּשִׁיבוּ אוֹתָם דָּבָר וְאֶת כָּל הָעֵדָה וַיַּרְאוּם אֶת פְּרִי הָאָרֶץ' AND `text_niqud_pisuq` = 'וַיֵּלְכוּ וַיָּבֹאוּ אֶל מֹשֶׁה וְאֶל אַהֲרֹן וְאֶל כָּל עֲדַת בְּנֵי-יִשְׂרָאֵל אֶל מִדְבַּר פָּארָן קָדֵשָׁה וַיָּשִׁיבוּ אוֹתָם דָּבָר וְאֶת כָּל הָעֵדָה וַיַּרְאוּם אֶת פְּרִי הָאָרֶץ.' AND `text_teamim` = '' AND `after_text` = '' AND `ktovt_prq` = 'prqim/t0413.htm' AND `ktovt_sikum` = 'sfr=04&prq=13&psuq=26' AND 1 LIMIT 1;

